const cardsData = [
  {         
    id: "monogatari-series-off-monster-season",
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/monogatari-series-off-monster-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Monogatari Series: Off & Monster Season",
    status: "Estado: en emisión",
    availability: "Disponible 0 capitulos",
    readMoreLink: "../2024/informacion/delicos-nursery.html",
    num:"194",
    },
    {
    id: "egumi-legacy",
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/egumi-legacy.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Egumi Legacy",         
    status: "Estado: en emisión",
    availability: "Disponible 0 capitulos",
    readMoreLink: "../2024/informacion/delicos-nursery.html",
    num:"194",       
    },
    {         
    id: "delicos-nursery",
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/delicos-nursery.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Delico's Nursery",
    status: "Estado: por estrenar",
    availability: "Disponible 0 capitulos",
    readMoreLink: "../2024/informacion/delicos-nursery.html",
    num:"194",       
    },       
    {
    id: "sengoku-youko-senma-konton-hen",
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/sengoku-youko-senma-konton-hen.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Sengoku Youko: Senma Konton-hen",
    status: "Estado: ",
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/sengoku-youko-senma-konton-hen.html",
    num:"193",
    },       
    {         
    id: "yami-shibai-13",
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/yami-shibai-13.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Yami Shibai 13",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/yami-shibai-13.html",         
    num:"192",
    },       
    {         
    id: "atri-my-dear-moments",       
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/atri-my-dear-moments.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Atri: My Dear Moments",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/atri-my-dear-moments.html",
    num:"191",
    },
    {         
    id: "make-heroine-ga-oosugiru",       
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/make-heroine-ga-oosugiru.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Make Heroine ga Oosugiru!",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/make-heroine-ga-oosugiru.html",         
    num:"190",       
    },       
    {         
    id: "kinnikuman-kanpeki-chujin-shiso-hen",       
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/kinnikuman-kanpeki-chujin-shiso-hen.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Kinnikuman: Kanpeki Chоujin Shiso-hen",         
    status: "Estado: ",   
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/kinnikuman-kanpeki-chujin-shiso-hen.html",         
    num:"189",       
    },
    {         
    id: "naze-boku-no-sekai-wo-daremo-oboeteinai-no-ka",       
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/naze-boku-no-sekai-wo-daremo-oboeteinai-no-ka.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Naze Boku no Sekai wo Daremo Oboeteinai no ka?",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/naze-boku-no-sekai-wo-daremo-oboeteinai-no-ka.html",         
    num:"188",       
    },       
    {         
    id: "bye-bye-earth",       
    imageSrc: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/bye-bye-earth.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Bye Bye, Earth",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/bye-bye-earth.html",         
    num:"187",       
    },       
    {         
    id: "kimi-to-boku-no-saigo-no-senjou-aruiwa-sekai-ga-hajimaru-seisen-season-ii",       
    imageSrc: "../../img/2024/kimi-to-boku-no-saigo-no-senjou-aruiwa-sekai-ga-hajimaru-seisen-season-ii.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Kimi to Boku no Saigo no Senjou, Aruiwa Sekai ga Hajimaru Seisen Season II",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "https://github.com/Animeotakuonline/inicio/blob/main/src/paginas/img/2024/kimi-to-boku-no-saigo-no-senjou-aruiwa-sekai-ga-hajimaru-seisen-season-ii.html",
    mirando:true,      
    num:"186",       
    },       
    {         
    id: "koi-wa-futago-de-warikirenai",       
    imageSrc: "../../img/2024/koi-wa-futago-de-warikirenai.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Koi wa Futago de Warikirenai",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/koi-wa-futago-de-warikirenai.html",         
    num:"185",       
    },       
    {         
    id: "isekai-shikkaku",       
    imageSrc: "../../img/2024/isekai-shikkaku.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Isekai Shikkaku",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/isekai-shikkaku.html",         
    num:"184",       
    },       
    {         
    id: "katsute-mahou-shoujo-to-aku-wa-tekitai-shiteita",       
    imageSrc: "../../img/2024/katsute-mahou-shoujo-to-aku-wa-tekitai-shiteita.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Katsute Mahou Shoujo to Aku wa Tekitai shiteita",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/katsute-mahou-shoujo-to-aku-wa-tekitai-shiteita.html",         
    num:"183",       
    },       
    {         
    id: "isekai-yururi-kikou-kosodateshinagara-boukensha-shimasu",       
    imageSrc: "../../img/2024/isekai-yururi-kikou-kosodateshinagara-boukensha-shimasu.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Isekai Yururi Kikou: Kosodateshinagara Boukensha Shimasu",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/isekai-yururi-kikou-kosodateshinagara-boukensha-shimasu.html",         
    num:"182",       
    },       
    {         
    id: "vtuber-nandaga-haishin-kiri-wasuretara-densetsu-ni-natteta",       
    imageSrc: "../../img/2024/vtuber-nandaga-haishin-kiri-wasuretara-densetsu-ni-natteta.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "VTuber Nandaga Haishin Kiri Wasuretara Densetsu ni Natteta",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/vtuber-nandaga-haishin-kiri-wasuretara-densetsu-ni-natteta.html",         
    num:"181",       
    },       
    {         
    id: "mayonaka-punch",       
    imageSrc: "../../img/2024/mayonaka-punch.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Mayonaka Punch",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/mayonaka-punch.html",         
    num:"180",       
    },       
    {         
    id: "kami-no-tou-ouji-no-kikan",       
    imageSrc: "../../img/2024/kami-no-tou-ouji-no-kikan.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Kami no Tou: Ouji no Kikan",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/kami-no-tou-ouji-no-kikan.html",
    mirando:true,
    num:"179",       
    },       
    {         
    id: "fairy-tail-100-nen-quest",       
    imageSrc: "../../img/2024/fairy-tail-100-nen-quest.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Fairy Tail: 100-nen Quest",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/fairy-tail-100-nen-quest.html",
    mirando:true,
    num:"178",       
    },       
    {         
    id: "shikanoko-nokonoko-koshitantan",       
    imageSrc: "../../img/2024/shikanoko-nokonoko-koshitantan.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Shikanoko Nokonoko Koshitantan",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/shikanoko-nokonoko-koshitantan.html",         
    mirando:true,
    num:"177",       
    },       
    {         
    id: "shoushimin-series",       
    imageSrc: "../../img/2024/shoushimin-series.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Shoushimin Series",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/shoushimin-series.html",         
    num:"176",       
    },       
    {         
    id: "tsue-to-tsurugi-no-wistoria",       
    imageSrc: "../../img/2024/tsue-to-tsurugi-no-wistoria.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Tsue to Tsurugi no Wistoria",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/tsue-to-tsurugi-no-wistoria.html",         
    num:"175",       
    },       
    {         
    id: "elf-san-wa-yaserarenai",       
    imageSrc: "../../img/2024/Elf-san-wa-Yaserarenai.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Elf-san wa Yaserarenai",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/Elf-san-wa-Yaserarenai.html",         
    num:"174",       
    },       
    {         
    id: "na-nare-hana-nare",       
    imageSrc: "../../img/2024/na-nare-hana-nare.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "Na Nare Hana Nare",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/na-nare-hana-nare.html",         
    num:"173",       
    },       
    {         
    id: "0-saiji-start-dash-monogatari",       
    imageSrc: "../../img/2024/0-saiji-start-dash-monogatari.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",         
    name: "0-saiji Start Dash Monogatari",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/0-saiji-start-dash-monogatari.html",         
    num:"172",       
    },       
    {         
    id: "nige-jouzu-no-wakagimi",       
    imageSrc: "../../img/2024/nige-jouzu-no-wakagimi.jpg",         
    dateAdded: "2024",         
    dateOfRelease: "Fecha de emisión: ",
    name: "Nige Jouzu no Wakagimi",         
    status: "Estado: ",         
    availability: "Disponible X capitulos",         
    readMoreLink: "../2024/informacion/nige-jouzu-no-wakagimi.html",         
    num:"171",       
    }, 
        
          
    
    
    
    
    
    
    
    
    {
    id: "madougushi-dahliya-wa-utsumukanai",
    imageSrc: "../../img/2024/madougushi-dahliya-wa-utsumukanai.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Madougushi Dahliya wa Utsumukanai",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/madougushi-dahliya-wa-utsumukanai.html",
    num: "170",
    },
    {
    id: "mob-kara-hajimaru-tansaku-eiyuutan",
    imageSrc: "../../img/2024/mob-kara-hajimaru-tansaku-eiyuutan.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Mob kara Hajimaru Tansaku Eiyuutan",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/mob-kara-hajimaru-tansaku-eiyuutan.html",
    mirando:true,
    num: "169",
    },
    {
    id: "kono-sekai-wa-fukanzen-sugiru",
    imageSrc: "../../img/2024/kono-sekai-wa-fukanzen-sugiru.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Kono Sekai wa Fukanzen Sugiru",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/kono-sekai-wa-fukanzen-sugiru.html",
    num: "168",
    },
    {
    id: "dungeon-no-naka-no-hito",
    imageSrc: "../../img/2024/dungeon-no-naka-no-hito.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Dungeon no Naka no Hito",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/dungeon-no-naka-no-hito.html",
    num: "167",
    },
    {
    id: "tensui-no-sakuna-hime",
    imageSrc: "../../img/2024/tensui-no-sakuna-hime.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Tensui no Sakuna-hime",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/tensui-no-sakuna-hime.html",
    num: "166",
    },
    {
    id: "grendizer-u",
    imageSrc: "../../img/2024/grendizer-u.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Grendizer U",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/grendizer-u.html",
    num: "165",
    },
    {
    id: "cardfight-vanguard-divinez-season-2",
    imageSrc: "../../img/2024/cardfight-vanguard-divinez-season-2.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Cardfight!! Vanguard: Divinez Season 2",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/cardfight-vanguard-divinez-season-2.html",
    num: "164",
    },
    {
    id: "nierautomata-ver11a-part-2",
    imageSrc: "../../img/2024/nierautomata-ver11a-part-2.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "NieR:Automata Ver1.1a Part 2",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/nierautomata-ver11a-part-2.html",
    mirando:true,
    num: "163",
    },
    {
    id: "25-jigen-no-ririsa",
    imageSrc: "../../img/2024/25-jigen-no-ririsa.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "2.5-jigen no Ririsa",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/25-jigen-no-ririsa.html",
    num: "162",
    },
    {
    id: "giji-harem",
    imageSrc: "../../img/2024/giji-harem.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Giji Harem",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/giji-harem.html",
    mirando:true,
    num: "161",
    },
    {
    id: "megami-no-cafe-terrace-2nd-season",
    imageSrc: "../../img/2024/megami-no-caf-terrace-2nd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Megami no Cafe Terrace 2nd Season",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/megami-no-cafe-terrace-2nd-season.html",
    mirando:true,
    num: "160",
    },
    {
    id: "senpai-wa-otokonoko",
    imageSrc: "../../img/2024/senpai-wa-otokonoko.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Senpai wa Otokonoko",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/senpai-wa-otokonoko.html",
    mirando:true,
    num: "159",
    },
    {
    id: "hazurewaku-no-joutai-ijou-skill-de-saikyou-ni-natta-ore-ga-subete-wo-juurin-suru-made",
    imageSrc: "../../img/2024/hazurewaku-no-joutai-ijou-skill-de-saikyou-ni-natta-ore-ga-subete-wo-juurin-suru-made.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Hazurewaku no 'Joutai Ijou Skill' de Saikyou ni Natta Ore ga Subete wo Juurin suru made",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/hazurewaku-no-joutai-ijou-skill-de-saikyou-ni-natta-ore-ga-subete-wo-juurin-suru-made.html",
    num: "158",
    },
    {
    id: "ore-wa-subete-wo-parry-suru-gyaku-kanchigai-no-sekai-saikyou-wa-boukensha-ni-naritai",
    imageSrc: "../../img/2024/ore-wa-subete-wo-parry-suru-gyaku-kanchigai-no-sekai-saikyou-wa-boukensha-ni-naritai.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Ore wa Subete wo 'Parry' suru: Gyaku Kanchigai no Sekai Saikyou wa Boukensha ni Naritai",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/ore-wa-subete-wo-parry-suru-gyaku-kanchigai-no-sekai-saikyou-wa-boukensha-ni-naritai.html",
    num: "157",
    },
    {
    id: "gimai-seikatsu",
    imageSrc: "../../img/2024/gimai-seikatsu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Gimai Seikatsu",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/gimai-seikatsu.html",
    mirando:true,
    num: "156",
    },
    {
    id: "tasogare-out-focus",
    imageSrc: "../../img/2024/tasogare-out-focus.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Tasogare Out Focus",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/tasogare-out-focus.html",
    num: "155",
    },
    {
    id: "ramen-akaneko",
    imageSrc: "../../img/2024/ramen-akaneko.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Ramen Akaneko",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/ramen-akaneko.html",
    num: "154",
    },
    {
    id: "oshi-no-ko-2nd-season",
    imageSrc: "../../img/2024/oshi-no-ko-2nd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "'Oshi no Ko' 2nd Season",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/oshi-no-ko-2nd-season.html",
    mirando:true,
    num: "153",
    },
    {
    id: "tokidoki-bosotto-russia-go-de-dereru-tonari-no-alya-san",
    imageSrc: "../../img/2024/tokidoki-bosotto-russia-go-de-dereru-tonari-no-alya-san.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Tokidoki Bosotto Russia-go de Dereru Tonari no Alya-san",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/tokidoki-bosotto-russia-go-de-dereru-tonari-no-alya-san.html",
    mirando:true,
    num: "152",
    },
    {
    id: "maougun-saikyou-no-majutsushi-wa-ningen-datta",
    imageSrc: "../../img/2024/maougun-saikyou-no-majutsushi-wa-ningen-datta.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Maougun Saikyou no Majutsushi wa Ningen datta",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/maougun-saikyou-no-majutsushi-wa-ningen-datta.html",
    num: "151",
    },
    {
    id: "tasuuketsu",
    imageSrc: "../../img/2024/tasuuketsu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Tasuuketsu",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/tasuuketsu.html",
    mirando:true,
    num: "150",
    },
    {
    id: "boku-no-tsuma-wa-kanjou-ga-nai",
    imageSrc: "../../img/2024/boku-no-tsuma-wa-kanjou-ga-nai.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Boku no Tsuma wa Kanjou ga Nai",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/boku-no-tsuma-wa-kanjou-ga-nai.html",
    mirando:true,
    num: "149",
    },
    {
    id: "shy-2nd-season",
    imageSrc: "../../img/2024/shy-2nd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Shy 2nd Season",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/shy-2nd-season.html",
    mirando:true,
    num: "148",
    },
    {
    id: "shinmai-ossan-boukensha-saikyou-party-ni-shinu-hodo-kitaerarete-muteki-ni-naru",
    imageSrc: "../../img/2024/shinmai-ossan-boukensha-saikyou-party-ni-shinu-hodo-kitaerarete-muteki-ni-naru.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Shinmai Ossan Boukensha, Saikyou Party ni Shinu hodo Kitaerarete Muteki ni Naru",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/shinmai-ossan-boukensha-saikyou-party-ni-shinu-hodo-kitaerarete-muteki-ni-naru.html",
    num: "147",
    },
    {
    id: "isekai-suicide-squad",
    imageSrc: "../../img/2024/isekai-suicide-squad.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Isekai Suicide Squad",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"146",
    },
            
    {
    id: "code-geass-dakkan-no-rozé",
    imageSrc: "../../img/2024/code-geass-dakkan-no-roz.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Code Geass: Dakkan no Rozé",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"145",
    },
            
    {
    id: "jin-can-wangshi",
    imageSrc: "../../img/2024/jin-can-wangshi.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Jin Can Wangshi",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"144",
    },
            
    {
    id: "cong-gu-huo-niao-kaishi-long-cheng-fengyun",
    imageSrc: "../../img/2024/cong-gu-huo-niao-kaishi-long-cheng-fengyun.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Cong Gu Huo Niao Kaishi: Long Cheng Fengyun",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"143",
    },
            
    {
    id: "hanma-baki-vs-kengan-ashura",
    imageSrc: "../../img/2024/hanma-baki-vs-kengan-ashura.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Hanma Baki vs. Kengan Ashura",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"142",
    },
            
    {
    id: "quanzhi-gaoshou-3",
    imageSrc: "../../img/2024/quanzhi-gaoshou-3.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Quanzhi Gaoshou 3",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"141",
    },
            
    {
    id: "huan-chong-shi",
    imageSrc: "../../img/2024/huan-chong-shi.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: ",
    name: "Huan Chong Shi",
    status: "Estado: ",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"140",
    },
            
    {
    id: "dead-dead-demons-dededede-destruction-ona",
    imageSrc: "../../img/2024/dead-dead-demons-dededede-destruction-ona.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 24 de mayo del 2024",
    name: "Dead Dead Demons Dededede Destruction (ONA)",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"139",
    },
            
    {
    id: "garouden-the-way-of-the-lone-wolf",
    imageSrc: "../../img/2024/garouden-the-way-of-the-lone-wolf.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 23 de mayo del 2024",
    name: "Garouden: The Way of the Lone Wolf",
    status: "Estado: Finalizado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"138",
    },
            
    {
    id: "xiehou-ta-de-shaonu-shidai",
    imageSrc: "../../img/2024/xiehou-ta-de-shaonu-shidai.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 23 de mayo del 2024",
    name: "Xiehou Ta de Shaonu Shidai",
    status: "Estado: Finalizado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"137",
    },
            
    {
    id: "jinwu-wei-feng-qi-jinling",
    imageSrc: "../../img/2024/jinwu-wei-feng-qi-jinling.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 23 de mayo del 2024",
    name: "Jinwu Wei: Feng Qi Jinling",
    status: "Estado: Finalizado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"136",
    },
            
    {
    id: "you-shou-yan-3rd-season",
    imageSrc: "../../img/2024/you-shou-yan-3rd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 17 de mayo del 2024",
    name: "You Shou Yan 3rd Season",
    status: "Estado: en emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"135",
    },
            
    {
    id:"kimetsu-no-yaiba-hashira-geiko-hen",  
    imageSrc: "../../img/2024/kimetsu-no-yaiba-hashira-geiko-hen.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de mayo del 2024",
    name: "Kimetsu no Yaiba: Hashira Geiko-hen",
    status: "Estado: por estrenar",
    availability: "Disponible 0 capitulos de ??",
    readMoreLink: "../2024/informacion/Kimetsu-no-Yaiba-Hashira-Geiko-Hen.html",
    visto: true,    
    num:"134"
    },
            
    {
    id: "boku-no-hero-academia-7th-season",
    imageSrc: "../../img/2024/boku-no-hero-academia-7th-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 04 de mayo del 2024",
    name: "Boku no Hero Academia 7th Season",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Boku-no-Hero-Academia-7th-Season.html",
    mirando: true,
    num:"133",
    },
            
    {
    id: "jantama-kan",
    imageSrc: "../../img/2024/jantama-kan.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 25 de abril del 2024",
    name: "Jantama Kan",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Jantama-Kan!!.html",
    num:"132",
    },
            
    {
    id: "grimm-kumikyoku",
    imageSrc: "../../img/2024/grimm-kumikyoku.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 17 de abril del 2024",
    name: "Grimm Kumikyoku",
    status: "Estado: Finalizado",
    availability: "Disponible 6 capitulos",
    readMoreLink: "../2024/informacion/Grim- Kumikyoku.html",
    num:"131",
    },
            
    {
    id: "anhe-zhuan-part-2",
    imageSrc: "../../img/2024/anhe-zhuan-part-2.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 17 de abril del 2024",
    name: "Anhe Zhuan Part 2",
    status: "Estado: Finalizado",
    availability: "Disponible 6 capitulos",
    readMoreLink: "../2024/informacion/Grim- Kumikyoku.html",
    num:"130",
    },
            
    {
    id: "fanpai-chushihua",
    imageSrc: "../../img/2024/fanpai-chushihua.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de abril del 2024",
    name: "Fanpai Chushihua",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Kaijuu-8-gou.html",
    num:"129",
    },
            
    {
    id: "kaijuu-8-gou",
    imageSrc: "../../img/2024/kaijuu-8-gou.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de abril del 2024",
    name: "Kaijuu 8-gou",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Kaijuu-8-gou.html",
    num:"128",
    },
            
    {
    id: "sasayaku-you-ni-koi-wo-utau",
    imageSrc: "../../img/2024/sasayaku-you-ni-koi-wo-utau.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de abril del 2024",
    name: "Sasayaku You ni Koi wo Utau",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Kaijuu-8-gou.html",
    mirando:true,
    num:"127",
    },
            
    {
    id: "kuroshitsuji-kishuku-gakkou-hen",
    imageSrc: "../../img/2024/kuroshitsuji-kishuku-gakkou-hen.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de abril del 2024",
    name: "Kuroshitsuji: Kishuku Gakkou Hen",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Kuroshitsuji-Kishuku-Gakkou-Hen.html",
    num:"126",
    },
    
    {
    id: "the-new-gate",
    imageSrc: "../../img/2024/the-new-gate.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de abril del 2024",
    name: "The New Gate",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/the-new-gate.html",
    num:"125",
    },
            
    {
    id: "long-zu",
    imageSrc: "../../img/2024/long-zu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de abril del 2024",
    name: "Long Zu",
    status: "Estado: En emisión",
    availability: "Disponible 0 capitulos de ??",
    readMoreLink: "../2024/informacion/Long-Zu.html",
    num: "124",
    },
            
    {
    id: "maou-gakuin-no-futekigousha-shijou-saikyou-no-maou-no-shiso-tensei-shite-shison-tachi-no-gakkou-e-kayou-ii-part-2",
    imageSrc: "../../img/2024/maou-gakuin-no-futekigousha-shijou-saikyou-no-maou-no-shiso-tensei-shite-shison-tachi-no-gakkou-e-kayou-ii-part-2.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de abril del 2024",
    name: "Maou Gakuin no Futekigousha: Shijou Saikyou no Maou no Shiso, Tensei shite Shison-tachi no Gakkou e Kayou II - Part 2",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/maou-gakuin-no-futekigousha-shijou-saikyou-no-maou-no-shiso-tensei-shite-shison-tachi-no-gakkou-e-kayou-ii-part-2.html",
    mirando:true,
    num:"123",
    },
    
    
    {
    id: "the-idolmster-shiny-colors",
    imageSrc: "../../img/2024/the-idolmster-shiny-colors.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de abril del 2024",
    name: "The iDOLM@STER Shiny Colors",
    status: "Estado: En emisión",
    availability: "Disponible 0 capitulos de ??",
    readMoreLink: "../2024/informacion/the-idolmster-shiny-colors.html",
    visto:true,
    num: "122",
    },
    {
    id: "shadowverse-flame-arc-hen",
    imageSrc: "../../img/2024/shadowverse-flame-arc-hen.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de abril del 2024",
    name: "Shadowverse Flame: Arc-hen",
    status: "Estado: En emisiónr",
    availability: "Disponible 1 capitulo de 1",
    readMoreLink: "../2024/informacion/shadowverse-flame-arc-hen.html",
    num:"121",
    },
    {
    id: "kuramerukagari",
    imageSrc: "../../img/2024/kuramerukagari.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de abril del 2024",
    name: "Kuramerukagari",
    status: "Estado: Finalizado",
    availability: "Disponible 1 capitulos de 1",
    readMoreLink: "../2024/informacion/Kuramerukagari.html",
    num: "120",
    },
    {
    id: "kurayukaba",
    imageSrc: "../../img/2024/kurayukaba.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de abril del 2024",
    name: "kurayukaba",
    status: "Estado: Finalizado",
    availability: "Disponible 1 capitulos de 1",
    readMoreLink: "../2024/informacion/kurayukaba.html",
    num: "119",
    },
    {
    id: "kenka-dokugaku",
    imageSrc: "../../img/2024/kenka-dokugaku.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 11 de abril del 2024",
    name: "Kenka Dokugaku",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/kenka-dokugak.html",
    num:"118",
    },
    {
    id: "seiyuu-radio-no-uraomote",
    imageSrc: "../../img/2024/seiyuu-radio-no-uraomote.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de abril del 2024",
    name: "Seiyuu Radio no Uraomote",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/seiyuu-radio-no-uraomote.html",
    num:"117",
    },
    {
    id: "kono-subarashii-sekai-ni-shukufuku-wo-3",
    imageSrc: "../../img/2024/kono-subarashii-sekai-ni-shukufuku-wo-3.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de abril del 2024",
    name: "Kono Subarashii Sekai ni Shukufuku wo! 3",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/kono-subarashii-sekai-ni-shukufuku-wo-3.html",
    visto: true,
    num:"116",
    },
    {
    id: "date-a-live-v",
    imageSrc: "../../img/2024/date-a-live-v.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de abril del 2024",
    name: "Date A Live V",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/date-a-live-v.html",
    visto:"true",
    num:"115",
    },
    {
    id: "kaii-to-otome-to-kamikakushi",
    imageSrc: "../../img/2024/kaii-to-otome-to-kamikakushi.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de abril del 2024",
    name: "Kaii to Otome to Kamikakushi",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/kaii-to-otome-to-kamikakushi.html",
    num:"114",
    },
    {
    id: "xuwu-bianjing",
    imageSrc: "../../img/2024/xuwu-bianjing.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de abril del 2024",
    name: "xuwu bianjing",
    status: "Estado: En emisión",
    availability: "Disponible 0 capitulos de ??",
    readMoreLink: "../2024/informacion/xuwu-bianjing.html",
    num: "113",
    },
    {
    id: "unnamed-memory",
    imageSrc: "../../img/2024/unnamed-memory.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 09 de abrl del 2024",
    name: "Unnamed: Memory",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Unnamed-Memory.html",
    num:"112",
    },
    {
    id: "boukyaku-battery-tv",
    imageSrc: "../../img/2024/boukyaku-battery-tv.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 09 de abril del 2024",
    name: "Boukyaku Battery (TV)",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/boukyaku-battery-tv.html",
    por_ver: true,
    num:"111",
    },
    {
    id: "rinkai",
    imageSrc: "../../img/2024/rinkai.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 09 de abril del 2024",
    name: "Rinkai!",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/rinkai.html",
    num:"110",
    },
    {
    id: "lv2-kara-cheat-datta-motoyuusha-kouho-no-mattari-isekai-life",
    imageSrc: "../../img/2024/lv2-kara-cheat-datta-motoyuusha-kouho-no-mattari-isekai-life.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de abril del 2024",
    name: "Lv2 kara Cheat datta Motoyuusha Kouho no Mattari Isekai Life",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/lv2-kara-cheat-datta-motoyuusha-kouho-no-mattari-isekai-life.html",
    num:"109",
    },
    {
    id: "tadaima-okaeri",
    imageSrc: "../../img/2024/tadaima-okaeri.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de abril del 2024",
    name: "Tadaima, Okaeri",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/tadaima-okaeri.html",
    num:"108",
    },
    {
    id: "shen-zhiyi-jiao",
    imageSrc: "../../img/2024/shen-zhiyi-jiao.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de abril del 2024",
    name: "Shen Zhiyi Jiao",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/tadaima-okaeri.html",
    num:"107",
    },
    {
    id: "mushoku-tensei-ii-isekai-ittara-honki-dasu-part-2",
    imageSrc: "../../img/2024/mushoku-tensei-ii-isekai-ittara-honki-dasu-part-2.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de abril del 2024",
    name: "Mushoku Tensei: Isekai Ittara Honki Dasu Part 2",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/mushoku-tensei-ii-isekai-ittara-honki-dasu-part-2.html",
    visto:true,
    num:"106",
    },
    {
    id: "hibike-euphonium-3",
    imageSrc: "../../img/2024/hibike-euphonium-3.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Hibike! Euphonium 3",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/hibike-euphonium-3.html",
    visto:true,
    num:"105",
    },
    {
    id: "sentai-daishikkaku",
    imageSrc: "../../img/2024/sentai-daishikkaku.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Sentai Daishikkaku",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/sentai-daishikkaku.html",
    num:"104",
    },
    {
    id: "yozakura-san-chi-no-daisakusen",
    imageSrc: "../../img/2024/yozakura-san-chi-no-daisakusen.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Yozakura-san Chi no Daisakusen",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/yozakura-san-chi-no-daisakusen.html",
    num:"103",
    },
    {
    id: "jiisan-baasan-wakagaeru",
    imageSrc: "../../img/2024/jiisan-baasan-wakagaeru.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Jiisan Baasan Wakagaeru",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/jiisan-baasan-wakagaeru.html",
    num:"102",
    },
    {
    id: "shinigami-bocchan-to-kuro-maid-3rd-season",
    imageSrc: "../../img/2024/shinigami-bocchan-to-kuro-maid-3rd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Shinigami Bocchan to Kuro Maid 3rd Season",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/shinigami-bocchan-to-kuro-maid-3rd-season.html",
    num:"101",
    },
    {
    id: "tensei-kizoku-kantei-skill-de-nariagaru",
    imageSrc: "../../img/2024/tensei-kizoku-kantei-skill-de-nariagaru.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Tensei Kizoku, Kantei Skill de Nariagaru",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/tensei-kizoku-kantei-skill-de-nariagaru.html",
    num:"100",
    },
    {
    id: "blue-archive-the-animation",
    imageSrc: "../../img/2024/blue-archive-the-animation.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Blue Archive the Animation",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/blue-archive-the-animation.html",
    por_ver:true,
    num:"99",
    },
    {
    id: "vampire-dormitory",
    imageSrc: "../../img/2024/vampire-dormitory.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Vampire Dormitory",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/vampire-dormitory.html",
    num:"98",
    },
    {
    id: "tonari-no-youkai-san",
    imageSrc: "../../img/2024/tonari-no-youkai-san.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Tonari no Youkai-san",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/tonari-no-youkai-san.html",
    num:"97",
    },
    {
    id: "ooi-tonbo",
    imageSrc: "../../img/2024/ooi-tonbo.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de abril del 2024",
    name: "Ooi! Tonbo",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"96",
    },
    {
    id: "himitsu-no-aipri",
    imageSrc: "../../img/2024/himitsu-no-aipri.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Himitsu no AiPri",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/himitsu-no-aipri.html",
    num:"95",
    },
    {
    id: "shinkalion-change-the-world",
    imageSrc: "https://cdn.jkdesu.com/assets/images/animes/image/shinkalion-change-the-world.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Shinkalion: Change the World",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/shinkalion-change-the-world.html",
    num:"94",
    },
    {
    id: "yoru-no-kurage-wa-oyogenai",
    imageSrc: "../../img/2024/yoru-no-kurage-wa-oyogenai.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "Yoru no Kurage wa Oyogenai",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/yoru-no-kurage-wa-oyogenai.html",
    num:"93",
    },
    {
    id: "the-fable",
    imageSrc: "../../img/2024/the-fable.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de abril del 2024",
    name: "The Fable",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/the-fable.html",
    num:"92",
    },
    {
    id: "highspeed-etoile",
    imageSrc: "../../img/2024/highspeed-etoile.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de abril del 2024",
    name: "Highspeed Etoile",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"91",
    },
    {
    id: "karasu-wa-aruji-wo-erabanai",
    imageSrc: "../../img/2024/karasu-wa-aruji-wo-erabanai.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de abril del 2024",
    name: "Karasu wa Aruji wo Erabanai",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"90",
    },
    {
    id: "boku-no-hero-academia-memories",
    imageSrc: "https://cdn.jkdesu.com/assets/images/animes/image/boku-no-hero-academia-memories.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de abril del 2024",
    name: "Boku no Hero Academia: Memories",
    status: "Estado: En emisión",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    visto:true,
    num:"89",
    },
    {
    id: "tensei-shitara-slime-datta-ken-3rd-season",
    imageSrc: "../../img/2024/tensei-shitara-slime-datta-ken-3rd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de abril del 2024",
    name: "Tensei shitara Slime Datta Ken 3rd Season",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Tensei shitara Slime Datta Ken 3rd Season.html",
    mirando:true,
    num:"88",
    },
    {
    id: "mahouka-koukou-no-rettousei-3rd-season",
    imageSrc: "../../img/2024/mahouka-koukou-no-rettousei-3rd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 01 de abril del 2024",
    name: "Mahouka Koukou no Rettousei 3rd Season",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Mahouka Koukou no Rettousei 3rd Season.html",
    visto:true,
    num:"87",
    },
    {
    id: "girls-band-cry",
    imageSrc: "../../img/2024/girls-band-cry.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de abril del 2024",
    name: "Girls Band Cry",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"86",
    },
    {
    id: "astro-note",
    imageSrc: "../../img/2024/astro-note.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de abril del 2024",
    name: "Astro Note",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"85",
    },
    {
    id: "henjin-no-salad-bowl",
    imageSrc: "../../img/2024/henjin-no-salad-bowl.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de abril del 2024",
    name: "Henjin no Salad Bowl",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"84",
    },
    {
    id: "nijiyon-animation-2",
    imageSrc: "../../img/2024/nijiyon-animation-2.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de abril del 2024",
    name: "Nijiyon Animation 2",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"83",
    },
    {
    id: "yuru-camp-season-3",
    imageSrc: "../../img/2024/yuru-camp-season-3.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 04 de abril del 2024",
    name: "Yuru Camp△ Season 3",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Yuru Camp Season 3.html",
    visto:true,
    num:"82",
    },
    {
    id: "hananoi-kun-to-koi-no-yamai",
    imageSrc: "../../img/2024/hananoi-kun-to-koi-no-yamai.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión:04 de abril del 2024",
    name: "Hananoi-kun to Koi no Yamai",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Hananoi-kun to Koi no Yamai.html",
    visto:true,
    num:"81",
    },
    {
    id: "wind-breaker",
    imageSrc: "../../img/2024/wind-breaker.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de abril del 2024",
    name: "Wind Breaker",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Wind Breaker.html",
    num:"80",
    },
    {
    id: "bartender-kami-no-glass",
    imageSrc: "../../img/2024/bartender-kami-no-glass.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 04 de bril del 2024",
    name: "Bartender: Kami no Glass",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"79",
    },
    {
    id: "maou-no-ore-ga-dorei-elf-wo-yome-ni-shitanda-ga-dou-medereba-ii",
    imageSrc: "https://cdn.jkdesu.com/assets/images/animes/image/maou-no-ore-ga-dorei-elf-wo-yome-ni-shitanda-ga-dou-medereba-ii.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 04 de bril del 2024",
    name: "Maou no Ore ga Dorei Elf wo Yome ni Shitanda ga, Dou Medereba Ii?",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    visto:true,
    num:"78",
    },
    {
    id: "touken-ranbu-kai-kyoden-moyuru-honnouji",
    imageSrc: "../../img/2024/touken-ranbu-kai-kyoden-moyuru-honnouji.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 02 de abril del 2024",
    name: "Touken Ranbu Kai Kyoden Moyuru Honnouji",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"77",
    },
    {
    id: "ookami-to-koushinryou-merchant-meets-the-wise-wolf",
    imageSrc: "../../img/2024/ookami-to-koushinryou-merchant-meets-the-wise-wolf.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 01 de abril del 2024",
    name: "Ookami to Koushinryou: Merchant Meets the Wise Wolf",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Ookami to Koushinryou Merchant Meets the Wise Wolf.html",
    num:"76",
    },
    {
    id: "tensei-shitara-dainana-ouji-datta-node-kimama-ni-majutsu-wo-kiwamemasu",
    imageSrc: "../../img/2024/tensei-shitara-dainana-ouji-datta-node-kimama-ni-majutsu-wo-kiwamemasu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 02 de abril del 2024",
    name: "Tensei shitara Dainana Ouji Datta node, Kimama ni Majutsu wo Kiwamemasu",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"75",
    },//------------------------------------------------------------------------------------------------------------------------------------------
    {
    id: "kami-wa-game-ni-ueteiru",
    imageSrc: "../../img/2024/kami-wa-game-ni-ueteiru.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 01 de abril del 2024",
    name: "Kami wa Game ni Ueteiru.",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    visto:true,
    num:"74",
    },
    {
    id: "remonster",
    imageSrc: "../../img/2024/remonster.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de abril del 2024",
    name: "Re:Monster",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"73",
    },
    {
    id: "dekisokonai-to-yobareta-motoeiyuu-wa-jikka-kara-tsuihou-sareta-node-sukikatte-ni-ikiru-koto-ni-shita",
    imageSrc: "../../img/2024/dekisokonai-to-yobareta-motoeiyuu-wa-jikka-kara-tsuihou-sareta-node-sukikatte-ni-ikiru-koto-ni-shita.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 02 de abril del 2024",
    name: "Dekisokonai to Yobareta Motoeiyuu wa Jikka kara Tsuihou sareta node Sukikatte ni Ikiru Koto ni Shita",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"72",
    },
    {
    id: "shuumatsu-train-doko-e-iku",
    imageSrc: "../../img/2024/shuumatsu-train-doko-e-iku.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 01 de abril del 2024",
    name: "Shuumatsu Train Doko e Iku?",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    por_ver:true,
    num:"71",
    },
    {
    id: "one-room-hiatari-futsuu-tenshi-tsuki",
    imageSrc: "../../img/2024/one-room-hiatari-futsuu-tenshi-tsuki.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 30 de mayo del 2024",
    name: "One Room, Hiatari Futsuu, Tenshi-tsuki.",
    status: "Estado: por estrenar",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    visto:true,
    num:"70",
    },
    {
    id: "sand-land-the-series",
    imageSrc: "../../img/2024/sand-land-the-series.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 20 de marzo del 2024",
    name: "Sand Land: The Series",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"69",
    },
    {
    id: "watashi-no-shiawase-na-kekkon-watashi-no-shiawase-na-katachi",
    imageSrc: "https://cdn.jkdesu.com/assets/images/animes/image/watashi-no-shiawase-na-kekkon-watashi-no-shiawase-na-katachi.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 15 de marzo del 2024",
    name: "Watashi no Shiawase na Kekkon: Watashi no Shiawase na Katachi",
    status: "Estado: finalizado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"68",
    },
    {
    id: "xiao-lu-he-xiao-lan-5th-season",
    imageSrc: "https://cdn.jkdesu.com/assets/images/animes/image/xiao-lu-he-xiao-lan-5th-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de marzo del 2024",
    name: "Xiao Lu He Xiao Lan 5th Season",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"67",
    },
    {
    id: "hanhua-riji-4th-season",
    imageSrc: "https://cdn.jkdesu.com/assets/images/animes/image/hanhua-riji-4th-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de marzo del 2024",
    name: "Hanhua Riji 4th Season",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"66",
    },
    {
    id: "bai-jia-jue-zhi-jianghu-gui-shi-lu",
    imageSrc: "../../img/2024/bai-jia-jue-zhi-jianghu-gui-shi-lu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 20 de marzo del 2024",
    name: "Bai Jia Jue Zhi: Jianghu Gui Shi Lu",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"65",
    },
    {
    id: "bu-xing-si-yuan-qi",
    imageSrc: "../../img/2024/bu-xing-si-yuan-qi.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 29 de febrero del 2024",
    name: "Bu Xing Si Yuan Qi",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Bu Xing Si Yuan Qi.html",
    num:"64",
    },
    {
    id: "great-pretender-razbliuto",
    imageSrc: "../../img/2024/great-pretender-razbliuto.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 23 de abril del 2024",
    name: "Great Pretender: Razbliuto",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Great Pretender Razbliuto.html",
    num:"63",
    },
    {
    id: "yishi-zhi-zun",
    imageSrc: "../../img/2024/yishi-zhi-zun.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 18 de febrero del 2024",
    name: "Yishi Zhi Zun",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Yishi Zhi Zun.html",
    num:"62",
    },
    {
    id: "aishang-ta-de-liyou-extra",
    imageSrc: "../../img/2024/aishang-ta-de-liyou-extra.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de febrero del 2024",
    name: "Aishang Ta de Liyou: Extra",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Aishang Ta de Liyou Extra.html",
    num:"61",
    },
    {
    id: "ninja-kamui",
    imageSrc: "../../img/2024/ninja-kamui.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 11 de febrero del 2024",
    name: "Ninja Kamui",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Ninja Kamui.html",
    num:"60",
    },
    {
      id: "wonderful-precure",
    imageSrc: "../../img/2024/wonderful-precure.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 04 de febrero del 2024",
    name: "Wonderful Precure",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Wonderful Precure.html",
    num:"59",
    },
    {
      id: "kui-cheng-shoufu-cong-youxi-kaishi",
    imageSrc: "../../img/2024/kui-cheng-shoufu-cong-youxi-kaishi.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 03 de abril del 2024",
    name: "Kui Cheng Shoufu: Cong Youxi Kaishi",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Kui Cheng Shoufu Cong Youxi Kaishi.html",
    num:"58",
    },
    {
      id: "taigu-xing-shen-jue",
    imageSrc: "../../img/2024/taigu-xing-shen-jue.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 25 de enero del 2024",
    name: "Taigu Xing Shen Jue",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Taigu Xing Shen Jue.html",
    num:"57",
    },
    {
      id: "yi-ren-jun-moye",
    imageSrc: "../../img/2024/yi-ren-jun-moye.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 24 de abril del 2024",
    name: "Yi Ren Jun Moye",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Yi Ren Jun Moye.html",
    num:"56",
    },
    {
      id: "sheng-zu",
    imageSrc: "../../img/2024/sheng-zu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 23 de abril del 2024",
    name: "Sheng Zu",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"55",
    },
    {
      id: "monsters-ippyaku-sanjou-hiryuu-jigoku",
    imageSrc: "../../img/2024/monsters-ippyaku-sanjou-hiryuu-jigoku.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 22 de enero del 2024",
    name: "Monsters: Ippyaku Sanjou Hiryuu Jigoku",
    status: "Estado: finalizado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Monsters Ippyaku Sanjou Hiryuu Jigoku.html",
    num:"54",
    },
    {
      id: "da-yuzhou-shidai",
    imageSrc: "../../img/2024/da-yuzhou-shidai.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 22 del enero del 2024",
    name: "Da Yuzhou Shidai",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/Da Yuzhou Shidai.html",
    num:"53",
    },
    {
      id: "meiji-gekken-1874",
    imageSrc: "../../img/2024/meiji-gekken-1874.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 14 de abril del 2024",
    name: "Meiji Gekken: 1874",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"52",
    },
    {
      id: "hikari-no-ou-2nd-season",
    imageSrc: "../../img/2024/hikari-no-ou-2nd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 14 de enero del 2024",
    name: "Hikari no Ou 2nd Season",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"51",
    },
    {
      id: "yami-shibai-12",
    imageSrc: "../../img/2024/yami-shibai-12.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 14 de enero del 2024",
    name: "Yami Shibai 12",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"50",
    },
    {
      id: "kingdom-5th-season",
    imageSrc: "../../img/2024/kingdom-5th-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de abril del 2024",
    name: "Kingdom 5th Season",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"49",
    },
    {
      id: "bucchigiri",
    imageSrc: "../../img/2024/bucchigiri.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de enero del 2024",
    name: "Bucchigiri?!",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"48",
    },
    {
      id: "cardfight-vanguard-divinez",
    imageSrc: "../../img/2024/cardfight-vanguard-divinez.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de enero del 2024",
    name: "Cardfight!! Vanguard: Divinez",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"47",
    },
    {
      id: "wangzhe-rongyao-rongyao-zhi-zhang",
    imageSrc: "../../img/2024/wangzhe-rongyao-rongyao-zhi-zhang.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 13 de enero del 2024",
    name: "Wangzhe Rongyao: Rongyao Zhi Zhang",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion",
    num:"46",
    }, 
    {
      id: "meitou-isekai-no-yu-kaitakuki-around-40-onsen-mania-no-tensei-saki-wa-nonbiri-onsen-tengoku-deshita",
    imageSrc: "../../img/2024/meitou-isekai-no-yu-kaitakuki-around-40-onsen-mania-no-tensei-saki-wa-nonbiri-onsen-tengoku-deshita.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de enero del 2024",
    name: "Meitou &quot;Isekai no Yu&quot; Kaitakuki: Around 40 Onsen Mania no Tensei Saki wa, Nonbiri Onsen Tengoku deshita",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"45",
    },  
    {
      id: "majo-to-yajuu",
    imageSrc: "../../img/2024/majo-to-yajuu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de enero del 2024",
    name: "Majo to Yajuu",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"44",
    },
    {
      id: "urusei-yatsura-2022-2nd-season",
    imageSrc: "../../img/2024/urusei-yatsura-2022-2nd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de enero del 2024",
    name: "Urusei Yatsura (2022) 2nd Season",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"43",
    },  
    {
      id: "saijaku-tamer-wa-gomi-hiroi-no-tabi-wo-hajimemashita",
    imageSrc: "../../img/2024/saijaku-tamer-wa-gomi-hiroi-no-tabi-wo-hajimemashita.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de enero del 2024",
    name: "Saijaku Tamer wa Gomi Hiroi no Tabi wo Hajimemashita",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"42",
    visto:true,
    },
    {
      id: "snack-basue",
    imageSrc: "../../img/2024/snack-basue.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 12 de enero del 2024",
    name: "Snack Basue",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"41",
    },
    {
      id: "gekkan-mousou-kagaku",
    imageSrc: "../../img/2024/gekkan-mousou-kagaku.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 11 de enero del 2024",
    name: "Gekkan Mousou Kagaku",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"40",
    },
    {
      id: "yuuki-bakuhatsu-bang-bravern",
    imageSrc: "../../img/2024/yuuki-bakuhatsu-bang-bravern.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 11 de enero del 2024",
    name: "Yuuki Bakuhatsu Bang Bravern",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"39",
    },
    {
      id: "metallic-rouge",
    imageSrc: "../../img/2024/metallic-rouge.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de enero del 2024",
    name: "Metallic Rouge",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"38",
    },  
    {
      id: "gekai-elise",
    imageSrc: "../../img/2024/gekai-elise.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de enero del 2024",
    name: "Gekai Elise",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"37",
    visto:true,
    },
    {
      id: "sengoku-youko",
    imageSrc: "../../img/2024/sengoku-youko.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de enero del 2024",
    name: "Sengoku Youko",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"36",
    },
    {
      id: "30-sai-made-doutei-dato-mahoutsukai-ni-nareru-rashii",
    imageSrc: "../../img/2024/30-sai-made-doutei-dato-mahoutsukai-ni-nareru-rashii.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 10 de enero del 2024",
    name: "30-sai made Doutei dato Mahoutsukai ni Nareru Rashii",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"35",
    },
    {
      id: "synduality-noir-part-2",
    imageSrc: "../../img/2024/synduality-noir-part-2.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 09 de enero del 2024",
    name: "Synduality: Noir Part 2",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"34",
    },
    {
      id: "akuyaku-reijou-level-99-watashi-wa-ura-boss-desu-ga-maou-dewa-arimasen",
    imageSrc: "../../img/2024/akuyaku-reijou-level-99-watashi-wa-ura-boss-desu-ga-maou-dewa-arimasen.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 09 de enero del 2024",
    name: "Akuyaku Reijou Level 99: Watashi wa Ura-Boss desu ga Maou dewa Arimasen",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    visto:true,
    num:"33",
    },  
    {
      id: "shaman-king-flowers",
    imageSrc: "../../img/2024/shaman-king-flowers.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 09 de enero del 2024",
    name: "Shaman King: Flowers",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"32",
    },
    {
      id: "tsuki-ga-michibiku-isekai-douchuu-2nd-season",
    imageSrc: "../../img/2024/tsuki-ga-michibiku-isekai-douchuu-2nd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de enero del 2024",
    name: "Tsuki ga Michibiku Isekai Douchuu 2nd Season",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    visto:true,
    num:"31",
    },
    {
      id: "dosanko-gal-wa-namara-menkoi",
    imageSrc: "../../img/2024/dosanko-gal-wa-namara-menkoi.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de enero del 2024",
    name: "Dosanko Gal wa Namara Menkoi",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"30",
    },
    {
      id: "oroka-na-tenshi-wa-akuma-to-odoru",
    imageSrc: "../../img/2024/oroka-na-tenshi-wa-akuma-to-odoru.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de enero del 2024",
    name: "Oroka na Tenshi wa Akuma to Odoru",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    visto: true,
    num:"29",
    },
    {
      id: "high-card-season-2",
    imageSrc: "../../img/2024/high-card-season-2.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de enero del 2024",
    name: "High Card Season 2",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"28",
    },
    {
      id: "nozomanu-fushi-no-boukensha",
    imageSrc: "../../img/2024/nozomanu-fushi-no-boukensha.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de enero del 2024",
    name: "Nozomanu Fushi no Boukensha",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"27",
    },
    {
    id: "himesama-goumon-no-jikan-desu",
    imageSrc: "../../img/2024/himesama-goumon-no-jikan-desu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 08 de enero del 2024",
    name: "Himesama &quot;Goumon&quot; no Jikan desu",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    por_ver:true,
    num:"26",
    },
    {
      id: "boku-no-kokoro-no-yabai-yatsu-season-2",
    imageSrc: "../../img/2024/boku-no-kokoro-no-yabai-yatsu-season-2.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de enero del 2024",
    name: "Boku no Kokoro no Yabai Yatsu Season 2",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    visto: true,//falta ver cap 13
    num:"25",
    },
    {
      id: "ao-no-exorcist-shimane-illuminati-hen",
    imageSrc: "../../img/2024/ao-no-exorcist-shimane-illuminati-hen.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de enero del 2024",
    name: "Ao no Exorcist: Shimane Illuminati-hen",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"24",
    },
    {
      id: "shin-no-nakama-ja-nai-to-yuusha-no-party-wo-oidasareta-node-henkyou-de-slow-life-suru-koto-ni-shimashita-2nd",
    imageSrc: "../../img/2024/shin-no-nakama-ja-nai-to-yuusha-no-party-wo-oidasareta-node-henkyou-de-slow-life-suru-koto-ni-shimashita-2nd.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de enero del 2024",
    name: "Shin no Nakama ja Nai to Yuusha no Party wo Oidasareta node, Henkyou de Slow Life suru Koto ni Shimashita 2nd",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    visto: true,
    num:"23",
    },
    {
      id: "loop-7-kaime-no-akuyaku-reijou-wa-moto-tekikoku-de-jiyuu-kimama-na-hanayome-seikatsu-wo-mankitsu-suru",
    imageSrc: "../../img/2024/loop-7-kaime-no-akuyaku-reijou-wa-moto-tekikoku-de-jiyuu-kimama-na-hanayome-seikatsu-wo-mankitsu-suru.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de enero del 2024",
    name: "Loop 7-kaime no Akuyaku Reijou wa, Moto Tekikoku de Jiyuu Kimama na Hanayome Seikatsu wo Mankitsu suru",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    visto:true,
    num:"22",
    },
    {
      id: "kyuujitsu-no-warumono-san",
    imageSrc: "../../img/2024/kyuujitsu-no-warumono-san.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de enero del 2024",
    name: "Kyuujitsu no Warumono-san",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"21",
    },
    {
      id: "saikyou-tank-no-meikyuu-kouryaku-tairyoku-9999-no-rare-skill-mochi-tank-yuusha-party-wo-tsuihou-sareru",
    imageSrc: "../../img/2024/saikyou-tank-no-meikyuu-kouryaku-tairyoku-9999-no-rare-skill-mochi-tank-yuusha-party-wo-tsuihou-sareru.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 07 de enero del 2024",
    name: "Saikyou Tank no Meikyuu Kouryaku: Tairyoku 9999 no Rare Skill-mochi Tank, Yuusha Party wo Tsuihou sareru",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"20",
    },
    {
      id: "ore-dake-level-up-na-ken",
    imageSrc: "../../img/2024/ore-dake-level-up-na-ken.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de enero del 2024",
    name: "Ore dake Level Up na Ken",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    visto: true,
    num:"19",
    },
    {
      id: "mashle-2nd-season",
    imageSrc: "../../img/2024/mashle-2nd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de enero del 2024",
    name: "Mashle 2nd Season",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"18",
    },
    {
      id: "yubisaki-to-renren",
    imageSrc: "../../img/2024/yubisaki-to-renren.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de enero del 2024",
    name: "Yubisaki to Renren",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    visto: true,
    num:"17",
    },
    {
      id: "kekkon-yubiwa-monogatari",
    imageSrc: "../../img/2024/kekkon-yubiwa-monogatari.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de enero del 2024",
    name: "Kekkon Yubiwa Monogatari",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"16",
    },
    {
      id: "pon-no-michi",
    imageSrc: "../../img/2024/pon-no-michi.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 06 de enero del 2024",
    name: "Pon no Michi",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"15",
    },
    {
      id: "sokushi-cheat-ga-saikyou-sugite-isekai-no-yatsura-ga-marude-aite-ni-naranai-n-desu-ga",
    imageSrc: "../../img/2024/sokushi-cheat-ga-saikyou-sugite-isekai-no-yatsura-ga-marude-aite-ni-naranai-n-desu-ga.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de enero del 2024",
    name: "Sokushi Cheat ga Saikyou sugite, Isekai no Yatsura ga Marude Aite ni Naranai n desu ga",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"14",
    },
    {
      id: "chiyu-mahou-no-machigatta-tsukaikata",
    imageSrc: "../../img/2024/chiyu-mahou-no-machigatta-tsukaikata.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de enero del 2024",
    name: "Chiyu Mahou no Machigatta Tsukaikata",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"13",
    visto:true,
    },
    {
      id: "momochi-san-chi-no-ayakashi-ouji",
    imageSrc: "../../img/2024/momochi-san-chi-no-ayakashi-ouji.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de enero del 2024",
    name: "Momochi-san Chi no Ayakashi Ouji",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"12",
    },
    {
      id: "sasaki-to-pii-chan",
    imageSrc: "../../img/2024/sasaki-to-pii-chan.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de enero del 2024",
    name: "Sasaki to Pii-chan",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"11",
    },
    {
      id: "chou-futsuu-ken-chiba-densetsu",
    imageSrc: "../../img/2024/chou-futsuu-ken-chiba-densetsu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 05 de enero del 2024",
    name: "Chou Futsuu Ken Chiba Densetsu",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"10",
    },
    {
      id: "mato-seihei-no-slave",
    imageSrc: "../../img/2024/mato-seihei-no-slave.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 04 de enero del 2024",
    name: "Mato Seihei no Slave",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"9",
    },
    {
      id: "dungeon-meshi",
    imageSrc: "../../img/2024/dungeon-meshi.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 04 de enero del 2024",
    name: "Dungeon Meshi",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"8",
    },
    {
      id: "youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-3rd-season",
    imageSrc: "../../img/2024/youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-3rd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 03 de enero del 2024",
    name: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e 3rd Season",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    visto: true,
    num:"7",
    },
    {
      id: "jaku-chara-tomozaki-kun-2nd-stage",
    imageSrc: "../../img/2024/jaku-chara-tomozaki-kun-2nd-stage.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 03 de enero del 2024",
    name: "Jaku-Chara Tomozaki-kun 2nd Stage",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"6",
    },
    {
      id: "ishura",
    imageSrc: "../../img/2024/ishura.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 03 de enero del 2024",
    name: "Ishura",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"5",
    },
    {
      id: "mahou-shoujo-ni-akogarete",
    imageSrc: "../../img/2024/mahou-shoujo-ni-akogarete.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 03 de enero del 2024",
    name: "Mahou Shoujo ni Akogarete",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    por_ver:true,
    num:"4",
    },
    {
      id: "wu-nao-monu-2nd-season",
    imageSrc: "../../img/2024/wu-nao-monu-2nd-season.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 02 de enero del 2024",
    name: "Wu Nao Monu 2nd Season",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"3",
    },
    {
      id: "isekai-de-mofumofu-nadenade-suru-tame-ni-ganbattemasu",
    imageSrc: "../../img/2024/isekai-de-mofumofu-nadenade-suru-tame-ni-ganbattemasu.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 01 de enero del 2024",
    name: "Isekai de Mofumofu Nadenade suru Tame ni Ganbattemasu",
    status: "Estado: concluido",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"2",
    },
    {
      id: "wangu-kuang-di",
    imageSrc: "../../img/2024/wangu-kuang-di.jpg",
    dateAdded: "2024",
    dateOfRelease: "Fecha de emisión: 01 de enero del 2024",
    name: "Wangu Kuang Di",
    status: "Estado: en emision",
    availability: "Disponible X capitulos",
    readMoreLink: "../2024/informacion/",
    num:"1",
    },
    // Añade más tarjetas según sea necesario
    ];
// Función para agregar una tarjeta al contenedor
function addCard(cardData) {
  const container = document.getElementById('cardsContainer');
  if (!container) return;

  const visto = cardData.visto || false;
  const por_ver = cardData.por_ver || false;
  const mirando = cardData.mirando || false;

  const cardHTML = `
    <div id="${cardData.id}" class="p-4 w-full  border-red-100 border-opacity-60 rounded-lg">
      <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden ${visto ? 'bg-gradient-to-r from-yellow-500 to-yellow-600 text-white' : por_ver ? 'bg-gradient-to-b from-red-500 to-red-600 text-white' : mirando ? 'bg-gradient-to-b from-green-500 to-green-600 text-white' : 'bg-white text-black'}">
        <a href="${cardData.readMoreLink || '#'}">
          <img class="h-72 w-full object-cover object-center" src="${cardData.imageSrc}" alt="blog">
        </a>
        <div class="p-6">
          <h2 class="text-base font-medium text-indigo-300 mb-1">${cardData.dateAdded}</h2>
          <h2 class="text-base font-medium text-indigo-300 mb-1">${cardData.dateOfRelease}</h2>
          <h1 class="text-2xl font-semibold mb-3 sm:text-xl sm:card-title">${cardData.name}</h1>
          <h3 class="text-black hover:bg-gradient-to-l focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800 font-medium rounded-lg text-sm mr-2 mb-2">${cardData.status}</h3>
          <li class="py-3 sm:py-4">
            <div class="flex items-center space-x-3">
              <span class="inline-flex items-center bg-green-100 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">
                ${cardData.availability}
              </span>
            </div>
          </li>
          <div class="flex items-center flex-wrap">
            <a href="${cardData.readMoreLink || '#'}" class="${visto ? 'text-orange-400' : por_ver ? 'text-orange-400' : mirando ? 'text-orange-400' : 'text-blue-600'} inline-flex items-center md:mb-2 lg:mb-0">Leer Más
              <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  `;

  container.innerHTML += cardHTML;
}

// Función para mostrar tarjetas basadas en IDs
function displayCardsByIds(ids) {
  ids.forEach(id => {
    const cardData = cardsData.find(card => card.id === id);
    if (cardData) addCard(cardData);
  });
}

// Función para mostrar tarjetas con visto: true
function displayVistoCards() {
  cardsData.forEach(cardData => {
    if (cardData.visto) addCard(cardData);
  });
}

// Al cargar el contenido del DOM
document.addEventListener('DOMContentLoaded', function () {
  const container = document.getElementById('cardsContainer');
  if (container) {
    const showVistoOnly = container.getAttribute('data-show-visto-only') === 'true';
    const cardIds = container.getAttribute('data-card-ids').split(',');

    if (showVistoOnly) {
      displayVistoCards();
    } else {
      displayCardsByIds(cardIds);
    }
  }
});
