// Ejemplo de datos para las tarjetas (puedes adaptar esto según tus necesidades)
const cardsData = [ 
  {
    id:"gokushufudou-season-2",
    imageSrc: "../../img/2022/gokushufudou-season-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Gokushufudou Season 2",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"224",
  },
  {
    id:"tensei-oujo-to-tensai-reijou-no-mahou-kakumei",
    imageSrc: "../../img/2022/tensei-oujo-to-tensai-reijou-no-mahou-kakumei.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tensei Oujo to Tensai Reijou no Mahou Kakumei",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"223",
  },
  {
    id:"cang-lan-jue-part-2",
    imageSrc: "../../img/2022/cang-lan-jue-part-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Cang Lan Jue Part 2",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"222",
  },
  {
    id:"kaguya-sama-wa-kokurasetai-first-kiss-wa-owaranai",
    imageSrc: "../../img/2022/kaguya-sama-wa-kokurasetai-first-kiss-wa-owaranai.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kaguya-sama wa Kokurasetai: First Kiss wa Owaranai",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto: true,
    num:"221",
  },
  {
    id:"lupin-zero",
    imageSrc: "../../img/2022/lupin-zero.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Lupin Zero",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"220",
  },
  {
    id:"isekai-meikyuu-de-harem-wo-specials",
    imageSrc: "../../img/2022/isekai-meikyuu-de-harem-wo-specials.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Isekai Meikyuu de Harem wo Specials",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"219",
  },
  {
    id:"tensei-shitara-slime-datta-ken-movie-guren-no-kizuna-hen",
    imageSrc: "../../img/2022/tensei-shitara-slime-datta-ken-movie-guren-no-kizuna-hen.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tensei shitara Slime Datta Ken Movie: Guren no Kizuna-hen",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto: true,
    num:"218",
  },
  {
    id:"tonikaku-kawaii-seifuku",
    imageSrc: "../../img/2022/tonikaku-kawaii-seifuku.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tonikaku Kawaii: Seifuku",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto: true,
    num:"217",
  },
  {
    id:"suzume-no-tojimari",
    imageSrc: "../../img/2022/suzume-no-tojimari.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Suzume no Tojimari",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"216",
  },
  {
    id:"xue-yu-xin",
    imageSrc: "../../img/2022/xue-yu-xin.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Xue Yu Xin",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"215",
  },
  {
    id:"kancolle-itsuka-ano-umi-de",
    imageSrc: "../../img/2022/kancolle-itsuka-ano-umi-de.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "KanColle: Itsuka Ano Umi de",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto: true,
    num:"214",
  },
  {
    id:"arknights-reimei-zensou",
    imageSrc: "../../img/2022/arknights-reimei-zensou.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Arknights: Reimei Zensou",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"213",
  },
  {
    id:"romantic-killer",
    imageSrc: "../../img/2022/romantic-killer.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Romantic Killer",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"212",
  },
  {
    id:"fumetsu-no-anata-e-2nd-season",
    imageSrc: "../../img/2022/fumetsu-no-anata-e-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Fumetsu no Anata e 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"211",
  },
  {
    id:"sword-art-online-progressive-movie-kuraki-yuuyami-no-scherzo",
    imageSrc: "../../img/2022/sword-art-online-progressive-movie-kuraki-yuuyami-no-scherzo.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Sword Art Online: Progressive Movie - Kuraki Yuuyami no Scherzo",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"210",
  },
  {
    id:"4-nin-wa-sorezore-uso-wo-tsuku",
    imageSrc: "../../img/2022/4-nin-wa-sorezore-uso-wo-tsuku.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "4-nin wa Sorezore Uso wo Tsuku",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"209",
  },
  {
    id:"urusei-yatsura-2022",
    imageSrc: "../../img/2022/urusei-yatsura-2022.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Urusei Yatsura (2022)",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"208",
  },
  {
    id:"watashi-ni-tenshi-ga-maiorita-precious-friends",
    imageSrc: "../../img/2022/watashi-ni-tenshi-ga-maiorita-precious-friends.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Watashi ni Tenshi ga Maiorita! Precious Friends",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"207",
  },
  {
    id:"aru-asa-dummy-head-mic-ni-natteita-ore-kun-no-jinsei",
    imageSrc: "../../img/2022/aru-asa-dummy-head-mic-ni-natteita-ore-kun-no-jinsei.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Aru Asa Dummy Head Mic ni Natteita Ore-kun no Jinsei",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"206",
  },
  {
    id:"chainsaw-man",
    imageSrc: "../../img/2022/chainsaw-man.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Chainsaw Man",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"205",
  },
  {
    id:"renai-flops",
    imageSrc: "../../img/2022/renai-flops.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Renai Flops",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"204",
  },
  {
    id:"bleach-sennen-kessen-hen",
    imageSrc: "../../img/2022/bleach-sennen-kessen-hen.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Bleach: Sennen Kessen-hen",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"203",
  },
  {
    id:"cool-doji-danshi",
    imageSrc: "../../img/2022/cool-doji-danshi.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Cool Doji Danshi",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"202",
  },
  {
    id:"eternal-boys",
    imageSrc: "../../img/2022/eternal-boys.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Eternal Boys",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"201",
  }, 
  {
    id:"peter-grill-to-kenja-no-jikan-super-extra",
    imageSrc: "../../img/2022/peter-grill-to-kenja-no-jikan-super-extra.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Peter Grill to Kenja no Jikan: Super Extra",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"200",
  },
  {
    id:"yowamushi-pedal-limit-break",
    imageSrc: "../../img/2022/yowamushi-pedal-limit-break.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yowamushi Pedal: Limit Break",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"199",
  },
  {
    id:"blue-lock",
    imageSrc: "../../img/2022/blue-lock.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Blue Lock",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"198",
  },
  {
    id:"fuufu-ijou-koibito-miman",
    imageSrc: "../../img/2022/fuufu-ijou-koibito-miman.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Fuufu Ijou, Koibito Miman.",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"197",
  },
  {
    id:"bocchi-the-rock",
    imageSrc: "../../img/2022/bocchi-the-rock.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Bocchi the Rock!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"196",
  },
  {
    id:"mairimashita-iruma-kun-3rd-season",
    imageSrc: "../../img/2022/mairimashita-iruma-kun-3rd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Mairimashita! Iruma-kun 3rd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"195",
  },
  {
    id:"seiken-densetsu-legend-of-mana-the-teardrop-crystal",
    imageSrc: "../../img/2022/seiken-densetsu-legend-of-mana-the-teardrop-crystal.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Seiken Densetsu: Legend of Mana - The Teardrop Crystal",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"194",
  },
  {
    id:"akiba-maid-sensou",
    imageSrc: "../../img/2022/akiba-maid-sensou.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Akiba Maid Sensou",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"193",
  },
  {
    id:"megaton-kyuu-musashi-2nd-season",
    imageSrc: "../../img/2022/megaton-kyuu-musashi-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Megaton-kyuu Musashi 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"192",
  },
  {
    id:"boku-ga-aishita-subete-no-kimi-e",
    imageSrc: "../../img/2022/boku-ga-aishita-subete-no-kimi-e.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Boku ga Aishita Subete no Kimi e",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"191",
  },
  {
    id:"kimi-wo-aishita-hitori-no-boku-e",
    imageSrc: "../../img/2022/kimi-wo-aishita-hitori-no-boku-e.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kimi wo Aishita Hitori no Boku e",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"190",
  },
  {
    id:"mob-psycho-100-iii",
    imageSrc: "../../img/2022/mob-psycho-100-iii.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Mob Psycho 100 III",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"189",
  },
  {
    id:"muv-luv-alternative-2nd-season",
    imageSrc: "../../img/2022/muv-luv-alternative-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Muv-Luv Alternative 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"188",
  },
  {
    id:"do-it-yourself",
    imageSrc: "../../img/2022/do-it-yourself.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Do It Yourself!!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"187",
  },
  {
    id:"mushikaburi-hime",
    imageSrc: "../../img/2022/mushikaburi-hime.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Mushikaburi-hime",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"186",
  },
  {
    id:"yama-no-susume-next-summit",
    imageSrc: "../../img/2022/yama-no-susume-next-summit.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yama no Susume: Next Summit",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"185",
  },
  {
    id:"kage-no-jitsuryokusha-ni-naritakute",
    imageSrc: "../../img/2022/kage-no-jitsuryokusha-ni-naritakute.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kage no Jitsuryokusha ni Naritakute!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"184",
  },
  {
    id:"tensei-shitara-ken-deshita",
    imageSrc: "../../img/2022/tensei-shitara-ken-deshita.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tensei shitara Ken Deshita",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"183",
  },
  {
    id:"futoku-no-guild",
    imageSrc: "../../img/2022/futoku-no-guild.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Futoku no Guild",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"182",
  },
  {
    id:"human-bug-daigaku",
    imageSrc: "../../img/2022/human-bug-daigaku.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Human Bug Daigaku",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"181",
  },
  {
    id:"shinobi-no-ittoki",
    imageSrc: "../../img/2022/shinobi-no-ittoki.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shinobi no Ittoki",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"180",
  },
  {
    id:"vazzrock-the-animation",
    imageSrc: "../../img/2022/vazzrock-the-animation.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Vazzrock The Animation",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"179",
  },
  {
    id:"meitantei-conan-hannin-no-hanzawa-san",
    imageSrc: "../../img/2022/meitantei-conan-hannin-no-hanzawa-san.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Meitantei Conan: Hannin no Hanzawa-san",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"178",
  },
  {
    id:"golden-kamuy-4th-season",
    imageSrc: "../../img/2022/golden-kamuy-4th-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Golden Kamuy 4th Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"177",
  },
  {
    id:"shinmai-renkinjutsushi-no-tenpo-keiei",
    imageSrc: "../../img/2022/shinmai-renkinjutsushi-no-tenpo-keiei.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shinmai Renkinjutsushi no Tenpo Keiei",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"176",
  },
  {
    id:"poputepipikku-2nd-season",
    imageSrc: "../../img/2022/poputepipikku-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Poputepipikku 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"175",
  },
  {
    id:"idolish7-third-beat-part-2",
    imageSrc: "../../img/2022/idolish7-third-beat-part-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "IDOLiSH7: Third Beat! Part 2",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"174",
  },
  {
    id:"koukyuu-no-karasu",
    imageSrc: "../../img/2022/koukyuu-no-karasu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Koukyuu no Karasu",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"173",
  },
  {
    id:"yuusha-party-wo-tsuihou-sareta-beast-tamer-saikyoushu-no-nekomimi-shoujo-to-deau",
    imageSrc: "../../img/2022/yuusha-party-wo-tsuihou-sareta-beast-tamer-saikyoushu-no-nekomimi-shoujo-to-deau.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yuusha Party wo Tsuihou sareta Beast Tamer, Saikyoushu no Nekomimi Shoujo to Deau",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"172",
  },
  {
    id:"mobile-suit-gundam-the-witch-from-mercury",
    imageSrc: "../../img/2022/mobile-suit-gundam-the-witch-from-mercury.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Mobile Suit Gundam: The Witch from Mercury",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"171",
  },
  {
    id:"c-danchi",
    imageSrc: "../../img/2022/c-danchi.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "C Danchi",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"170",
  },
  {
    id:"berserk-ougon-jidai-hen-memorial-edition",
    imageSrc: "../../img/2022/berserk-ougon-jidai-hen-memorial-edition.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Berserk: Ougon Jidai-hen - Memorial Edition",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"169",
  },
  {
    id:"spy-x-family-part-2",
    imageSrc: "../../img/2022/spy-x-family-part-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Spy x Family Part 2",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"168",
  },
  {
    id:"boku-no-hero-academia-6th-season",
    imageSrc: "../../img/2022/boku-no-hero-academia-6th-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Boku no Hero Academia 6th Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"167",
  },
  {
    id:"uzaki-chan-wa-asobitai-double",
    imageSrc: "../../img/2022/uzaki-chan-wa-asobitai-double.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Uzaki-chan wa Asobitai! Double",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"166",
  },
  {
    id:"noumin-kanren-no-skill-bakka-agetetara-nazeka-tsuyoku-natta",
    imageSrc: "../../img/2022/noumin-kanren-no-skill-bakka-agetetara-nazeka-tsuyoku-natta.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Noumin Kanren no Skill bakka Agetetara Nazeka Tsuyoku Natta.",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"165",
  },
  {
    id:"uchi-no-shishou-wa-shippo-ga-nai",
    imageSrc: "../../img/2022/uchi-no-shishou-wa-shippo-ga-nai.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Uchi no Shishou wa Shippo ga Nai",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"164",
  },
  {
    id:"the-daily-life-of-the-inmortal-king-3nd-season",
    imageSrc: "../../img/2022/the-daily-life-of-the-inmortal-king-3nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "The Daily Life of the Immortal King 3",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"163",
  },
  {
    id:"ginga-eiyuu-densetsu-die-neue-these-sakubou",
    imageSrc: "../../img/2022/ginga-eiyuu-densetsu-die-neue-these-sakubou.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Ginga Eiyuu Densetsu: Die Neue These - Sakubou",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"162",
  },
  {
    id:"akuyaku-reijou-nanode-last-boss-wo-kattemimashita",
    imageSrc: "../../img/2022/akuyaku-reijou-nanode-last-boss-wo-kattemimashita.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Akuyaku Reijou nanode Last Boss wo Kattemimashita",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"161",
  },
  {
    id:"ame-wo-tsugeru-hyouryuu-danchi",
    imageSrc: "../../img/2022/ame-wo-tsugeru-hyouryuu-danchi.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Ame wo Tsugeru Hyouryuu Danchi",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"160",
  },
  {
    id:"cyberpunk-edgerunners",
    imageSrc: "../../img/2022/cyberpunk-edgerunners.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Cyberpunk: Edgerunners",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"159",
  },
  {
    id:"tian-mei-de-yao-hen",
    imageSrc: "../../img/2022/tian-mei-de-yao-hen.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tian Mei De Yao Hen",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"158",
  },
  {
    id:"d4dj-double-mix",
    imageSrc: "../../img/2022/d4dj-double-mix.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "D4DJ Double Mix",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"157",
  },
  {
    id:"one-piece-film-red",
    imageSrc: "../../img/2022/one-piece-film-red.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "One Piece Film: Red",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"156",
  },
  {
    id:"kakegurui-twin",
    imageSrc: "../../img/2022/kakegurui-twin.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kakegurui Twin",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"155",
  },
  {
    id:"fuuto-tantei",
    imageSrc: "../../img/2022/fuuto-tantei.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Fuuto Tantei",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"154",
  },
  {
    id:"hanhua-riji-3rd-season",
    imageSrc: "../../img/2022/hanhua-riji-3rd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Hanhua Riji 3rd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"153",
  },
  {
    id:"yowai-5000-nen-no-soushoku-dragon-iwarenaki-jaryuu-nintei",
    imageSrc: "../../img/2022/yowai-5000-nen-no-soushoku-dragon-iwarenaki-jaryuu-nintei.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yowai 5000-nen no Soushoku Dragon, Iwarenaki Jaryuu Nintei",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"152",
  },
  {
    id:"sasaki-to-miyano-koi-ni-kizuku-mae-no-chotto-shita-hanashi",
    imageSrc: "../../img/2022/sasaki-to-miyano-koi-ni-kizuku-mae-no-chotto-shita-hanashi.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Sasaki to Miyano: Koi ni Kizuku Mae no Chotto Shita Hanashi.",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"151",
  },
  {
    id:"saikin-yatotta-maid-ga-ayashii",
    imageSrc: "../../img/2022/saikin-yatotta-maid-ga-ayashii.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Saikin Yatotta Maid ga Ayashii",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"150",
  },
  {
    id:"dungeon-ni-deai-wo-motomeru-no-wa-machigatteiru-darou-ka-iv-shin-shou-meikyuu-hen",
    imageSrc: "../../img/2022/dungeon-ni-deai-wo-motomeru-no-wa-machigatteiru-darou-ka-iv-shin-shou-meikyuu-hen.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Dungeon ni Deai wo Motomeru no wa Machigatteiru Darou ka IV: Shin Shou - Meikyuu-hen",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"149",
  },
  {
    id:"love-live-superstar-2nd-season",
    imageSrc: "../../img/2022/love-live-superstar-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Love Live! Superstar!! 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"148",
  },
  {
    id:"cang-lan-jue",
    imageSrc: "../../img/2022/cang-lan-jue.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Cang Lan Jue",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"147",
  },
  {
    id:"hataraku-maou-sama-2",
    imageSrc: "../../img/2022/hataraku-maou-sama-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Hataraku Maou-sama!!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"146",
  },
  {
    id:"shine-post",
    imageSrc: "../../img/2022/shine-post.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shine Post",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"145",
  },
  {
    id:"orient-awajishima-gekitou-hen",
    imageSrc: "../../img/2022/orient-awajishima-gekitou-hen.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Orient: Awajishima Gekitou-hen",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"144",
  },
  {
    id:"isekai-yakkyoku",
    imageSrc: "../../img/2022/isekai-yakkyoku.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Isekai Yakkyoku",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"143",
  },
  {
    id:"hanabi-chan-wa-okuregachi",
    imageSrc: "../../img/2022/hanabi-chan-wa-okuregachi.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Hanabi-chan wa Okuregachi",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"142",
  },
  {
    id:"kuro-no-shoukanshi",
    imageSrc: "../../img/2022/kuro-no-shoukanshi.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kuro no Shoukanshi",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"141",
  },
  {
    id:"extreme-hearts",
    imageSrc: "../../img/2022/extreme-hearts.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Extreme Hearts",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"140",
  },
  {
    id:"kj-file",
    imageSrc: "../../img/2022/kj-file.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "KJ File",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"139",
  },
  {
    id:"bucchigire",
    imageSrc: "../../img/2022/bucchigire.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Bucchigire!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"138",
  },
  {
    id:"dr-stone-ryuusui",
    imageSrc: "../../img/2022/dr-stone-ryuusui.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Dr. Stone: Ryuusui",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"137",
  },
  {
    id:"shadows-house-2nd-season",
    imageSrc: "../../img/2022/shadows-house-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shadows House 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"136",
  },
  {
    id:"soredemo-ayumu-wa-yosetekuru",
    imageSrc: "../../img/2022/soredemo-ayumu-wa-yosetekuru.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Soredemo Ayumu wa Yosetekuru",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"135",
  },
  {
    id:"hoshi-no-samidare",
    imageSrc: "../../img/2022/hoshi-no-samidare.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Hoshi no Samidare",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"134",
  },
  {
    id:"yofukashi-no-uta",
    imageSrc: "../../img/2022/yofukashi-no-uta.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yofukashi no Uta",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"133",
  },
  {
    id:"shin-tennis-no-ouji-sama-u-17-world-cup",
    imageSrc: "../../img/2022/shin-tennis-no-ouji-sama-u-17-world-cup.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shin Tennis no Ouji-sama: U-17 World Cup",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"132",
  },
  {
    id:"made-in-abyss-retsujitsu-no-ougonkyou",
    imageSrc: "../../img/2022/made-in-abyss-retsujitsu-no-ougonkyou.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Made in Abyss: Retsujitsu no Ougonkyou",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"131",
  },
  {
    id:"isekai-meikyuu-de-harem-wo",
    imageSrc: "../../img/2022/isekai-meikyuu-de-harem-wo.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Isekai Meikyuu de Harem wo",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"130",
  },
  {
    id:"kumichou-musume-to-sewagakari",
    imageSrc: "../../img/2022/kumichou-musume-to-sewagakari.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kumichou Musume to Sewagakari",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"129",
  },
  {
    id:"isekai-ojisan",
    imageSrc: "../../img/2022/isekai-ojisan.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Isekai Ojisan",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"128",
  },
  {
    id:"jashin-chan-dropkick-x",
    imageSrc: "../../img/2022/jashin-chan-dropkick-x.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Jashin-chan Dropkick X",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"127",
  },
  {
    id:"mamahaha-no-tsurego-ga-motokano-datta",
    imageSrc: "../../img/2022/mamahaha-no-tsurego-ga-motokano-datta.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Mamahaha no Tsurego ga Motokano datta",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"126",
  },
  {
    id:"kinsou-no-vermeil-gakeppuchi-majutsushi-wa-saikyou-no-yakusai-to-mahou-sekai-wo-tsukisusumu",
    imageSrc: "../../img/2022/kinsou-no-vermeil-gakeppuchi-majutsushi-wa-saikyou-no-yakusai-to-mahou-sekai-wo-tsukisusumu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kinsou no Vermeil: Gakeppuchi Majutsushi wa Saikyou no Yakusai to Mahou Sekai wo Tsukisusumu",
    status: "Estado",
    availability: "Disponible X capitulos",
    visto:true,
    num:"125",
  },
  {
    id:"tokyo-mew-mew-new",
    imageSrc: "../../img/2022/tokyo-mew-mew-new.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tokyo Mew Mew New ♡",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"124",
  },
  {
    id:"warau-arsnotoria-sun",
    imageSrc: "../../img/2022/warau-arsnotoria-sun.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Warau Arsnotoria Sun!e",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"123",
  },
  {
    id:"overlord-iv",
    imageSrc: "../../img/2022/overlord-iv.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Overlord IV",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"122",
  },
  {
    id:"cardfight-vanguard-willdress",
    imageSrc: "../../img/2022/cardfight-vanguard-willdress.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Cardfight!! Vanguard: will+Dress",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"121",
  },
  {
    id:"meng-qi-shi-shen-huanxi-zhui-hun",
    imageSrc: "../../img/2022/meng-qi-shi-shen-huanxi-zhui-hun.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Meng Qi Shi Shen: Huanxi Zhui Hun",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"120",
  },
  {
    id:"tuanzimen-de-shiming",
    imageSrc: "../../img/2022/tuanzimen-de-shiming.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tuanzimen de Shiming",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"119",
  },
  {
    id:"youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-tv-2nd-season",
    imageSrc: "../../img/2022/youkoso-jitsuryoku-shijou-shugi-no-kyoushitsu-e-tv-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Youkoso Jitsuryoku Shijou Shugi no Kyoushitsu e (TV) 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"118",
  },
  {
    id:"tensei-kenja-no-isekai-life-dai-2-no-shokugyou-wo-ete-sekai-saikyou-ni-narimashita",
    imageSrc: "../../img/2022/tensei-kenja-no-isekai-life-dai-2-no-shokugyou-wo-ete-sekai-saikyou-ni-narimashita.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tensei Kenja no Isekai Life: Dai-2 no Shokugyou wo Ete, Sekai Saikyou ni Narimashita",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"117",
  },
  {
    id:"utawarerumono-futari-no-hakuoro",
    imageSrc: "../../img/2022/utawarerumono-futari-no-hakuoro.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Utawarerumono: Futari no Hakuoro",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"116",
  },
  {
    id:"renmei-kuugun-koukuu-mahou-ongakutai-luminous-witches",
    imageSrc: "../../img/2022/renmei-kuugun-koukuu-mahou-ongakutai-luminous-witches.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Renmei Kuugun Koukuu Mahou Ongakutai Luminous Witches",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"115",
  },
  {
    id:"prima-doll",
    imageSrc: "../../img/2022/prima-doll.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Prima Doll",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"114",
  },
  {
    id:"yurei-deco",
    imageSrc: "../../img/2022/yurei-deco.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yurei Deco",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"113",
  },
  {
    id:"engage-kiss",
    imageSrc: "../../img/2022/engage-kiss.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Engage Kiss",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"112",
  },
  {
    id:"kanojo-okarishimasu-2nd-season",
    imageSrc: "../../img/2022/kanojo-okarishimasu-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kanojo, Okarishimasu 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"111",
  },
  {
    id:"musashino",
    imageSrc: "../../img/2022/musashino.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Musashino!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"110",
  },
  {
    id:"kami-kuzuidol",
    imageSrc: "../../img/2022/kami-kuzuidol.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kami Kuzu☆Idol",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"109",
  },
  {
    id:"lycoris-recoil",
    imageSrc: "../../img/2022/lycoris-recoil.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Lycoris Recoil",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"108",
  },
  {
    id:"shoot-goal-to-the-future",
    imageSrc: "../../img/2022/shoot-goal-to-the-future.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shoot! Goal to the Future",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"107",
  },
  {
    id:"teppen",
    imageSrc: "../../img/2022/teppen.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Teppen!!!!!!!!!!!!!!!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"106",
  },
  {
    id:"bakuten-movie",
    imageSrc: "../../img/2022/bakuten-movie.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Bakuten!! Movie",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"105",
  },
  {
    id:"yuru-camp-movie",
    imageSrc: "../../img/2022/yuru-camp-movie.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yuru Camp△ Movie",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"104",
  },
  {
    id:"yuusha-yamemasu-kenshuu-ryokou-wa-mokuteki-wo-miushinau-na",
    imageSrc: "../../img/2022/yuusha-yamemasu-kenshuu-ryokou-wa-mokuteki-wo-miushinau-na.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yuusha, Yamemasu: Kenshuu Ryokou wa Mokuteki wo Miushinau na",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"103",
  },
  {
    id:"rwby-hyousetsu-teikoku",
    imageSrc: "../../img/2022/rwby-hyousetsu-teikoku.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "RWBY: Hyousetsu Teikoku",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"102",
  },
  {
    id:"boku-no-hero-academia-ona",
    imageSrc: "../../img/2022/boku-no-hero-academia-ona.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Boku no Hero Academia (ONA)",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"101",
  },
  {
    id:"dragon-ball-super-super-hero",
    imageSrc: "../../img/2022/dragon-ball-super-super-hero.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Dragon Ball Super: Super Hero",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"100",
  },
  {
    id:"karakai-jouzu-no-takagi-san-movie",
    imageSrc: "../../img/2022/karakai-jouzu-no-takagi-san-movie.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Karakai Jouzu no Takagi-san Movie",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"99",
  },
  {
    id:"inu-ou",
    imageSrc: "../../img/2022/inu-ou.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Inu-Ou",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"98",
  },
  {
    id:"zanting-rang-wo-cha-gonglue",
    imageSrc: "../../img/2022/zanting-rang-wo-cha-gonglue.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Zanting! Rang Wo Cha Gonglue",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"97",
  },
  {
    id:"5-toubun-no-hanayome-movie",
    imageSrc: "../../img/2022/5-toubun-no-hanayome-movie.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "5-toubun no Hanayome Movie",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"96",
  },
  {
    id:"shin-ikkitousen",
    imageSrc: "../../img/2022/shin-ikkitousen.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shin Ikkitousen",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"95",
  },
  {
    id:"bubble",
    imageSrc: "../../img/2022/bubble.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Bubble",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"94",
  },
  {
    id:"yuukoku-no-moriarty-ova",
    imageSrc: "../../img/2022/yuukoku-no-moriarty-ova.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yuukoku no Moriarty OVA",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"93",
  },
  {
    id:"zuihou-de-zhaohuan-shi",
    imageSrc: "../../img/2022/zuihou-de-zhaohuan-shi.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Zuihou de Zhaohuan Shi",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"92",
  },
  {
    id:"kakkou-no-iinazuke",
    imageSrc: "../../img/2022/kakkou-no-iinazuke.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kakkou no Iinazuke",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"91",
  },
  {
    id:"summertime-render",
    imageSrc: "../../img/2022/summertime-render.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Summertime Render",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"90",
  },
  {
    id:"kaginado-season-2",
    imageSrc: "../../img/2022/kaginado-season-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kaginado Season 2",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"89",
  },
  {
    id:"kyoukai-senki-part-2",
    imageSrc: "../../img/2022/kyoukai-senki-part-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kyoukai Senki Part 2",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"88",
  },
  {
    id:"honzuki-no-gekokujou-shisho-ni-naru-tame-ni-wa-shudan-wo-erandeiraremasen-3rd-season",
    imageSrc: "../../img/2022/honzuki-no-gekokujou-shisho-ni-naru-tame-ni-wa-shudan-wo-erandeiraremasen-3rd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Honzuki no Gekokujou: Shisho ni Naru Tame ni wa Shudan wo Erandeiraremasen 3rd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"87",
  },
  {
    id:"onipan",
    imageSrc: "../../img/2022/onipan.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Onipan!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"86",
  },
  {
    id:"kunoichi-tsubaki-no-mune-no-uchi",
    imageSrc: "../../img/2022/kunoichi-tsubaki-no-mune-no-uchi.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kunoichi Tsubaki no Mune no Uchi",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"85",
  },
  {
    id:"kawaii-dake-ja-nai-shikimori-san",
    imageSrc: "../../img/2022/kawaii-dake-ja-nai-shikimori-san.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kawaii dake ja Nai Shikimori-san",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"84",
  },
  {
    id:"kingdom-4th-season",
    imageSrc: "../../img/2022/kingdom-4th-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kingdom 4th Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"83",
  },
  {
    id:"kono-healer-mendokusai",
    imageSrc: "../../img/2022/kono-healer-mendokusai.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kono Healer, Mendokusai",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"82",
  },
  {
    id:"spy-x-family",
    imageSrc: "../../img/2022/spy-x-family.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Spy x Family",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"81",
  },
  {
    id:"dance-dance-danseur",
    imageSrc: "../../img/2022/dance-dance-danseur.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Dance Dance Danseur",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"80",
  },
  {
    id:"ao-ashi",
    imageSrc: "../../img/2022/ao-ashi.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Ao Ashi",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"79",
  },
  {
    id:"yatogame-chan-kansatsu-nikki-4th-season",
    imageSrc: "../../img/2022/yatogame-chan-kansatsu-nikki-4th-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yatogame-chan Kansatsu Nikki 4th Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"78",
  },
  {
    id:"komi-san-wa-comyushou-desu-2nd-season",
    imageSrc: "../../img/2022/komi-san-wa-comyushou-desu-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Komi-san wa, Comyushou desu. 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"77",
  },
  {
    id:"mahoutsukai-reimeiki",
    imageSrc: "../../img/2022/mahoutsukai-reimeiki.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Mahoutsukai Reimeiki",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"76",
  },
  {
    id:"machikado-mazoku-2-choume",
    imageSrc: "../../img/2022/machikado-mazoku-2-choume.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Machikado Mazoku: 2-choume",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"75",
  },
  {
    id:"date-a-live-iv",
    imageSrc: "../../img/2022/date-a-live-iv.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Date A Live IV",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"74",
  },
  {
    id:"koi-wa-sekai-seifuku-no-ato-de",
    imageSrc: "../../img/2022/koi-wa-sekai-seifuku-no-ato-de.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Koi wa Sekai Seifuku no Ato de",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"73",
  },
  {
    id:"shachiku-san-wa-youjo-yuurei-ni-iyasaretai",
    imageSrc: "../../img/2022/shachiku-san-wa-youjo-yuurei-ni-iyasaretai.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shachiku-san wa Youjo Yuurei ni Iyasaretai.",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"72",
  },
  {
    id:"gaikotsu-kishi-sama-tadaima-isekai-e-odekakechuu",
    imageSrc: "../../img/2022/gaikotsu-kishi-sama-tadaima-isekai-e-odekakechuu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Gaikotsu Kishi-sama, Tadaima Isekai e Odekakechuu",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"71",
  },
  {
    id:"heroine-tarumono-kiraware-heroine-to-naisho-no-oshigoto",
    imageSrc: "../../img/2022/heroine-tarumono-kiraware-heroine-to-naisho-no-oshigoto.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Heroine Tarumono! Kiraware Heroine to Naisho no Oshigoto",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"70",
  },
  {
    id:"tomodachi-game",
    imageSrc: "../../img/2022/tomodachi-game.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tomodachi Game",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"69",
  },
  {
    id:"shijou-saikyou-no-daimaou-murabito-a-ni-tensei-suru",
    imageSrc: "../../img/2022/shijou-saikyou-no-daimaou-murabito-a-ni-tensei-suru.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shijou Saikyou no Daimaou, Murabito A ni Tensei suru",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"68",
  },
  {
    id:"tate-no-yuusha-no-nariagari-season-2",
    imageSrc: "../../img/2022/tate-no-yuusha-no-nariagari-season-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tate no Yuusha no Nariagari Season 2",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"67",
  },
  {
    id:"rpg-fudousan",
    imageSrc: "../../img/2022/rpg-fudousan.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "RPG Fudousan",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"66",
  },
  {
    id:"deaimon",
    imageSrc: "../../img/2022/deaimon.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Deaimon",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"65",
  },
  {
    id:"birdie-wing-golf-girls-story",
    imageSrc: "../../img/2022/birdie-wing-golf-girls-story.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Birdie Wing: Golf Girls' Story",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"64",
  },
  {
    id:"meitantei-conan-zero-no-tea-time",
    imageSrc: "../../img/2022/meitantei-conan-zero-no-tea-time.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Meitantei Conan: Zero no Tea Time",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"63",
  },
  {
    id:"paripi-koumei",
    imageSrc: "../../img/2022/paripi-koumei.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Paripi Koumei",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"62",
  },
  {
    id:"yuusha-yamemasu",
    imageSrc: "../../img/2022/yuusha-yamemasu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Yuusha, Yamemasu",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"61",
  },
  {
    id:"healer-girl",
    imageSrc: "../../img/2022/healer-girl.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Healer Girl",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"60",
  },
  {
    id:"otome-game-sekai-wa-mob-ni-kibishii-sekai-desu",
    imageSrc: "../../img/2022/otome-game-sekai-wa-mob-ni-kibishii-sekai-desu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Otome Game Sekai wa Mob ni Kibishii Sekai desu",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"59",
  },
  {
    id:"build-divide-code-white",
    imageSrc: "../../img/2022/build-divide-code-white.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Build Divide: Code White",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"58",
  },
  {
    id:"magia-record-mahou-shoujo-madokamagica-gaiden-tv-final-season-asaki-yume-no-akatsuki",
    imageSrc: "../../img/2022/magia-record-mahou-shoujo-madokamagica-gaiden-tv-final-season-asaki-yume-no-akatsuki.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Magia Record: Mahou Shoujo Madoka☆Magica Gaiden (TV) Final Season - Asaki Yume no Akatsuki",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"57",
  },
  {
    id:"blackrock-shooter-dawn-fall",
    imageSrc: "../../img/2022/blackrock-shooter-dawn-fall.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Black★★Rock Shooter: Dawn Fall",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"56",
  },
  {
    id:"rikei-ga-koi-ni-ochita-no-de-shoumei-shitemita-heart",
    imageSrc: "../../img/2022/rikei-ga-koi-ni-ochita-no-de-shoumei-shitemita-heart.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Rikei ga Koi ni Ochita no de Shoumei shitemita. Heart",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"55",
  },
  {
    id:"aharen-san-wa-hakarenai",
    imageSrc: "../../img/2022/aharen-san-wa-hakarenai.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Aharen-san wa Hakarenai",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"54",
  },
  {
    id:"jantama-pong",
    imageSrc: "../../img/2022/jantama-pong.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Jantama Pong☆",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"53",
  },
  {
    id:"shokei-shoujo-no-virgin-road",
    imageSrc: "../../img/2022/shokei-shoujo-no-virgin-road.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shokei Shoujo no Virgin Road",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"52",
  },
  {
    id:"love-all-play",
    imageSrc: "../../img/2022/love-all-play.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Love All Play",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"51",
  },
  {
    id:"love-live-nijigasaki-gakuen-school-idol-doukoukai-2nd-season",
    imageSrc: "../../img/2022/love-live-nijigasaki-gakuen-school-idol-doukoukai-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Love Live! Nijigasaki Gakuen School Idol Doukoukai 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"50",
  },
  {
    id:"gunjou-no-fanfare",
    imageSrc: "../../img/2022/gunjou-no-fanfare.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Gunjou no Fanfare",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"49",
  },
  {
    id:"shadowverse-flame",
    imageSrc: "../../img/2022/shadowverse-flame.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shadowverse Flame",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"48",
  },
  {
    id:"kaguya-sama-wa-kokurasetai-ultra-romantic",
    imageSrc: "../../img/2022/kaguya-sama-wa-kokurasetai-ultra-romantic.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kaguya-sama wa Kokurasetai: Ultra Romantic",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"47",
  },
  {
    id:"odd-taxi-movie-in-the-woods",
    imageSrc: "../../img/2022/odd-taxi-movie-in-the-woods.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Odd Taxi Movie: In the Woods",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"46",
  },
  {
    id:"strike-the-blood-final",
    imageSrc: "../../img/2022/strike-the-blood-final.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Strike the Blood Final",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"45",
  },
  {
    id:"kirakira-kirari",
    imageSrc: "../../img/2022/kirakira-kirari.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kirakira Kirari",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"44",
  },
  {
    id:"estab-life-great-escape",
    imageSrc: "../../img/2022/estab-life-great-escape.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Estab-Life: Great Escape",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"43",
  },
  {
    id:"non-non-biyori-nonstop-ova",
    imageSrc: "../../img/2022/non-non-biyori-nonstop-ova.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Non Non Biyori Nonstop OVA",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"42",
  },
  {
    id:"arifureta-shokugyou-de-sekai-saikyou-2nd-season-special",
    imageSrc: "../../img/2022/arifureta-shokugyou-de-sekai-saikyou-2nd-season-special.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Arifureta Shokugyou de Sekai Saikyou 2nd Season Special",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"41",
  },
  {
    id:"mushoku-tensei-isekai-ittara-honki-dasu-special",
    imageSrc: "../../img/2022/mushoku-tensei-isekai-ittara-honki-dasu-special.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Mushoku Tensei: Isekai Ittara Honki Dasu Special",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"40",
  },
  {
    id:"totsukuni-no-shoujo-2022",
    imageSrc: "../../img/2022/totsukuni-no-shoujo-2022.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Totsukuni no Shoujo (2022)",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"39",
  },
  {
    id:"ginga-eiyuu-densetsu-die-neue-these-gekitotsu",
    imageSrc: "../../img/2022/ginga-eiyuu-densetsu-die-neue-these-gekitotsu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Ginga Eiyuu Densetsu: Die Neue These - Gekitotsu",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"38",
  },
  {
    id:"ryuukyuu-timeline-2-tedako-no-machi-tanbou",
    imageSrc: "../../img/2022/ryuukyuu-timeline-2-tedako-no-machi-tanbou.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Ryuukyuu Timeline 2: Tedako no Machi Tanbou",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"37",
  },
  {
    id:"fruits-basket-prelude",
    imageSrc: "../../img/2022/fruits-basket-prelude.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Fruits Basket: Prelude",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"36",
  },
  {
    id:"delicious-partyprecure",
    imageSrc: "../../img/2022/delicious-partyprecure.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Delicious Party Precure",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"35",
  },
  {
    id:"rymans-club",
    imageSrc: "../../img/2022/rymans-club.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Ryman's Club",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"34",
  },
  {
    id:"tales-of-luminaria-the-fateful-crossroad",
    imageSrc: "../../img/2022/tales-of-luminaria-the-fateful-crossroad.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tales of Luminaria: The Fateful Crossroad",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"33",
  },
  {
    id:"kobayashi-san-chi-no-maidragon-s-nippon-no-omotenashi-attend-wa-dragon-desu",
    imageSrc: "../../img/2022/kobayashi-san-chi-no-maidragon-s-nippon-no-omotenashi-attend-wa-dragon-desu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kobayashi-san Chi no Maidragon S: Nippon no Omotenashi - Attend wa Dragon Desu",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"32",
  },
  {
    id:"vanitas-no-karte-2nd-season",
    imageSrc: "../../img/2022/vanitas-no-karte-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Vanitas no Karte 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"31",
  },
  {
    id:"arifureta-shokugyou-de-sekai-saikyou-2nd-season",
    imageSrc: "../../img/2022/arifureta-shokugyou-de-sekai-saikyou-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Arifureta Shokugyou de Sekai Saikyou 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"30",
  },
  {
    id:"koroshi-ai",
    imageSrc: "../../img/2022/koroshi-ai.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Koroshi Ai",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"29",
  },
  {
    id:"kenja-no-deshi-wo-nanoru-kenja",
    imageSrc: "../../img/2022/kenja-no-deshi-wo-nanoru-kenja.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kenja no Deshi wo Nanoru Kenja",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"28",
  },
  {
    id:"fantasy-bishoujo-juniku-ojisan-to",
    imageSrc: "../../img/2022/fantasy-bishoujo-juniku-ojisan-to.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Fantasy Bishoujo Juniku Ojisan to",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"27",
  },
  {
    id:"princess-connect-redive-season-2",
    imageSrc: "../../img/2022/princess-connect-redive-season-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Princess Connect! Re:Dive Season 2",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"26",
  },
  {
    id:"tensai-ouji-no-akaji-kokka-saisei-jutsu",
    imageSrc: "../../img/2022/tensai-ouji-no-akaji-kokka-saisei-jutsu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tensai Ouji no Akaji Kokka Saisei Jutsu",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"25",
  },
  {
    id:"sabikui-bisco",
    imageSrc: "../../img/2022/sabikui-bisco.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Sabikui Bisco",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"24",
  },
  {
    id:"gensou-sangokushi-tengen-reishinki",
    imageSrc: "../../img/2022/gensou-sangokushi-tengen-reishinki.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Gensou Sangokushi: Tengen Reishinki",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"23",
  },
  {
    id:"shingeki-no-kyojin-the-final-season-part-2",
    imageSrc: "../../img/2022/shingeki-no-kyojin-the-final-season-part-2.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shingeki no Kyojin: The Final Season Part 2",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"22",
  },
  {
    id:"sasaki-to-miyano",
    imageSrc: "../../img/2022/sasaki-to-miyano.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Sasaki to Miyano",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"21",
  },
  {
    id:"tribe-nine",
    imageSrc: "../../img/2022/tribe-nine.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tribe Nine",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"20",
  },
  {
    id:"genjitsu-shugi-yuusha-no-oukoku-saikenki-2nd-season",
    imageSrc: "../../img/2022/genjitsu-shugi-yuusha-no-oukoku-saikenki-2nd-season.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Genjitsu Shugi Yuusha no Oukoku Saikenki 2nd Season",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"19",
  },
  {
    id:"sono-bisque-doll-wa-koi-wo-suru",
    imageSrc: "../../img/2022/sono-bisque-doll-wa-koi-wo-suru.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Sono Bisque Doll wa Koi wo Suru",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    visto:true,
    num:"18",
  },
  {
    id:"baraou-no-souretsu",
    imageSrc: "../../img/2022/baraou-no-souretsu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Baraou no Souretsu",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"17",
  },
  {
    id:"akebi-chan-no-sailor-fuku",
    imageSrc: "../../img/2022/akebi-chan-no-sailor-fuku.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Akebi-chan no Sailor-fuku",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"16",
  },
  {
    id:"futsal-boys",
    imageSrc: "../../img/2022/futsal-boys.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Futsal Boys!!!!!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"15",
  },
  {
    id:"kaijin-kaihatsu-bu-no-kuroitsu-san",
    imageSrc: "../../img/2022/kaijin-kaihatsu-bu-no-kuroitsu-san.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Kaijin Kaihatsu-bu no Kuroitsu-san",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"14",
  },
  {
    id:"sabiiro-no-armor-reimei",
    imageSrc: "../../img/2022/sabiiro-no-armor-reimei.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Sabiiro no Armor: Reimei",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"13",
  },
  {
    id:"shuumatsu-no-harem",
    imageSrc: "../../img/2022/shuumatsu-no-harem.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shuumatsu no Harem",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"12",
  },
  {
    id:"karakai-jouzu-no-takagi-san-3",
    imageSrc: "../../img/2022/karakai-jouzu-no-takagi-san-3.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Karakai Jouzu no Takagi-san 3",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"11",
  },
  {
    id:"shikkakumon-no-saikyou-kenja",
    imageSrc: "../../img/2022/shikkakumon-no-saikyou-kenja.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Shikkakumon no Saikyou Kenja",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"10",
  },
  {
    id:"dolls-frontline",
    imageSrc: "../../img/2022/dolls-frontline.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Dolls' Frontline",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"9",
  },
  {
    id:"cue",
    imageSrc: "../../img/2022/cue.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Cue!",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"8",
  },
  {
    id:"slow-loop",
    imageSrc: "../../img/2022/slow-loop.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Slow Loop",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"7",
  },
  {
    id:"orient",
    imageSrc: "../../img/2022/orient.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Orient",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"6",
  },
  {
    id:"saiyuuki-reload-zeroin",
    imageSrc: "../../img/2022/saiyuuki-reload-zeroin.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Saiyuuki Reload: Zeroin",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"5",
  },
  {
    id:"tokyo-24-ku",
    imageSrc: "../../img/2022/tokyo-24-ku.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Tokyo 24-ku",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"4",
  },
  {
    id:"leadale-no-daichi-nite",
    imageSrc: "../../img/2022/leadale-no-daichi-nite.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Leadale no Daichi nite",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"3",
  },
  {
    id:"hakozume-kouban-joshi-no-gyakushuu",
    imageSrc: "../../img/2022/hakozume-kouban-joshi-no-gyakushuu.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Hakozume: Kouban Joshi no Gyakushuu",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    num:"2",
  },
  {
    id:"irodorimidori",
    imageSrc: "../../img/2022/irodorimidori.jpg",
    dateAdded: "2022",
    dateOfRelease: "Fecha de emisión",
    name: "Irodorimidori",
    status: "Estado",
    availability: "Disponible X capitulos",
    readMoreLink: "../2022/informacion/",
    por_ver:true,
    num:"1",
  },
      // Agrega más objetos según sea necesario
  ];

 // Función para agregar una tarjeta al contenedor
 // Función para agregar una tarjeta al contenedor
function addCard(cardData) {
  const container = document.getElementById('cardsContainer');
  if (!container) return;

  const visto = cardData.visto || false;
  const por_ver = cardData.por_ver || false;
  const mirando = cardData.mirando || false;

  const cardHTML = `
    <div id="${cardData.id}" class="p-4 w-full  border-red-100 border-opacity-60 rounded-lg">
      <div class="h-full border-2 border-gray-200 border-opacity-60 rounded-lg overflow-hidden ${visto ? 'bg-gradient-to-r from-yellow-500 to-yellow-600 text-white' : por_ver ? 'bg-gradient-to-b from-red-500 to-red-600 text-white' : mirando ? 'bg-gradient-to-b from-green-500 to-green-600 text-white' : 'bg-white text-black'}">
        <a href="${cardData.readMoreLink || '#'}">
          <img class="h-72 w-full object-cover object-center" src="${cardData.imageSrc}" alt="blog">
        </a>
        <div class="p-6">
          <h2 class="text-base font-medium text-indigo-300 mb-1">${cardData.dateAdded}</h2>
          <h2 class="text-base font-medium text-indigo-300 mb-1">${cardData.dateOfRelease}</h2>
          <h1 class="text-2xl font-semibold mb-3 sm:text-xl sm:card-title">${cardData.name}</h1>
          <h3 class="text-black hover:bg-gradient-to-l focus:ring-4 focus:outline-none focus:ring-purple-200 dark:focus:ring-purple-800 font-medium rounded-lg text-sm mr-2 mb-2">${cardData.status}</h3>
          <li class="py-3 sm:py-4">
            <div class="flex items-center space-x-3">
              <span class="inline-flex items-center bg-green-100 text-green-800 text-xs font-medium mr-2 px-2.5 py-0.5 rounded-full dark:bg-green-900 dark:text-green-300">
                ${cardData.availability}
              </span>
            </div>
          </li>
          <div class="flex items-center flex-wrap">
            <a href="${cardData.readMoreLink || '#'}" class="${visto ? 'text-orange-400' : por_ver ? 'text-orange-400' : mirando ? 'text-orange-400' : 'text-blue-600'} inline-flex items-center md:mb-2 lg:mb-0">Leer Más
              <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                <path d="M5 12h14"></path>
                <path d="M12 5l7 7-7 7"></path>
              </svg>
            </a>
          </div>
        </div>
      </div>
    </div>
  `;

  container.innerHTML += cardHTML;

  
}

function displayCardsByIds(ids) {
  ids.forEach(id => {
    const cardData = cardsData.find(card => card.id === id);
    if (cardData) addCard(cardData);
  });
}

document.addEventListener('DOMContentLoaded', function () {
  const container = document.getElementById('cardsContainer');
  const cardIds = container.getAttribute('data-card-ids').split(',');

  // Llamada a la función para mostrar las tarjetas específicas
  displayCardsByIds(cardIds);
});